#!/usr/bin/env bash
name='libsoup3'
release='2'
version='3.6.5'
url='https://gitlab.gnome.org/GNOME/libsoup.git/'
description='HTTP client/server library for GNOME '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libsoup/-/archive/$version/libsoup-$version.tar.gz")
depends=(smartypants glib-networking)
makedepends=(py3-packaging)
sha256sums=('a97f88f9182db8dd7b46afc139a0ff19e463cf4a9f799682e8c4189cbd5815c4')
group=(net.libs)
uses=()
arch=('x86_64')

cd libsoup-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

