#!/usr/bin/env bash
name='qt6-multimedia'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Qt6 - Multimedia support'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtmultimedia-everywhere-src-${version}.tar.xz")
depends=(qt6-base alsa-lib ffmpeg libpulse gst-plugins-base gst-plugins-bad libXrandr qt6-declarative qt6-quick3d)
makedepends=(cmake perl qt6-declarative)
sha256sums=('390f8e52ddee3aca5c4de7eead900c84c4fa61ff6d1f0ebea9c7543365c09b0a')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtmultimedia-everywhere-src-"${version}
export PATH=$PATH:/usr/bin/qt6


export CXXFLAGS="$CXXFLAGS -g1 -flto=auto -ffat-lto-objects"

setup() {
	cmake -B build -G Ninja \
      -DCMAKE_MESSAGE_LOG_LEVEL=STATUS \
			-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	cmake --build build
}

package () {
	DESTDIR="$DESTDIR" cmake --install build
	DESTDIR="$DESTDIR" cmake --install build/src/plugins/multimedia/gstreamer
	DESTDIR="$DESTDIR" cmake --install build/src/plugins/multimedia/ffmpeg
}