#!/usr/bin/env bash
name='qt6-wayland'
release='5'
version='6.11.1'
url='https://www.qt.io/developers/'
description='Provides APIs for Wayland'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwayland-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative libXcomposite libxkbcommon)
makedepends=(vulkan-headers cmake wayland)
sha256sums=('95788aa502f75441d4edf65932b235f76523084e13dbbb7b9ee2d207b32bd9b3')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwayland-everywhere-src-"$version
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
