#!/usr/bin/env bash
name='kcrash'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Support for application crash analysis and bug report from apps'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcrash-${version}.tar.xz")
depends=(qt6-base kcoreaddons)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( 'f8e1083863dac2c07068b10614ca7d4b52c6920df0228854cfc37e0d6578d902' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

