#!/usr/bin/env bash
name='breeze-gtk'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Artwork, styles and assets for the Breeze visual style for the Plasma Desktop'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/breeze-gtk-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules sassc py3-cairo breeze)
sha256sums=( '28599e177b4166a7b332f834a72696cf882cf9f6a9ee192708a27f474c1027c0' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
