#!/usr/bin/env bash
name='kguiaddons'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtGui'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kguiaddons-${version}.tar.xz")
depends=(qt6-base qt6-wayland qt6-declarative)
makedepends=(extra-cmake-modules doxygen qt6-tools plasma-wayland-protocols)
sha256sums=( '29b043480c45d3e51c57cac74fd83589cc7729c907a6585b72880cbf07feaf82' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
        -DBUILD_PYTHON_BINDINGS=OFF \
		    -DCMAKE_INSTALL_PREFIX=/usr \
		    -DCMAKE_INSTALL_LIBDIR=lib \
		    -DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
