#!/usr/bin/env bash
name='plasma-wayland-protocols'
release='5'
version='1.21.0'
url='https://www.kde.org/plasma-desktop/'
description='Plasma Specific Protocols for Wayland'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-${version}.tar.xz")
depends=()
makedepends=(qt6-base extra-cmake-modules)
sha256sums=( '698a7b28b711270314e396e248ae86087cfeaed01372009063995be6e1dc85ba' )
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr \
			-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

