#!/usr/bin/env bash
name='libXaw'
release='2'
version='1.0.16'
url='https://example.org'
description='Package libXaw'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXaw-$version.tar.gz")
depends=(libXext libXt libXmu libXpm)
makedepends=()
sha256sums=('012f90adf8739f2f023d63a5fee1528949cf2aba92ef7ac1abcfc2ae9cf28798')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

