#!/usr/bin/env bash
name='sqlite'
release='5'
version='3.51.2'
url='https://www.sqlite.org/download.html'
description='A C library that implements an SQL database engine'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
srcver='3510200'
source=("https://www.sqlite.org/2026/sqlite-src-$srcver.zip")
depends=(zlib readline)
makedepends=( )
sha256sums=('85110f762d5079414d99dd5d7917bc3ff7e05876e6ccbd13d8496a3817f20829')
uses=()
group=(dev.db)
arch=('x86_64')

cd $name-src-$srcver

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-fts3 \
        --enable-fts4 \
        --enable-fts5 \
        --enable-rtree \
        CPPFLAGS="-DSQLITE_ENABLE_FTS3=1            \
                  -DSQLITE_ENABLE_FTS4=1            \
                  -DSQLITE_ENABLE_COLUMN_METADATA=1 \
                  -DSQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                  -DSQLITE_ENABLE_DBSTAT_VTAB=1     \
                  -DSQLITE_SECURE_DELETE=1          \
                  -DSQLITE_ENABLE_FTS3_TOKENIZER=1"
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

