#!/usr/bin/env bash
name='cmake'
release='9'
version='4.2.3'
url='https://github.com/Kitware/CMake'
description='A cross-platform open-source make system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('7efaccde8c5a6b2968bad6ce0fe60e19b6e10701a12fce948c2bf79bac8a11e9')
uses=()
uses_extra=(qt)
group=(dev.util)
arch=('x86_64')

cd $name-$version

setup(){
    ./bootstrap --prefix=/usr \
        --no-system-libs \
        $(use_opt qt --qt-gui --no-qt-gui) \
        --parallel=`nproc`
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

