#!/usr/bin/env bash
name='pango'
release='3'
version='1.56.4'
url='https://metacpan.org/pod/Pango'
description='Layout and render international text'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/pango/1.56/pango-$version.tar.xz")
depends=(fribidi libthai harfbuzz cairo libXft)
makedepends=(gobject-introspection)
sha256sums=('17065e2fcc5f5a5bdbffc884c956bfc7c451a96e8c4fb2f8ad837c6413cb5a01')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

export LDFLAGS="-lfreetype"
setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dintrospection=enabled \
        -Dcairo=enabled \
        -Dlibthai=enabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

