#!/usr/bin/env bash
name='kgamma'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description="Adjust your monitor's gamma settings"
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kgamma-${version}.tar.xz")
depends=(kcmutils kconfig kcoreaddons ki18n libX11 libXxf86vm qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'e8c33dba47da3ea0f89053e9402982ab1fbdb69c259bf08b1047a0504b07dd92' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

