#!/usr/bin/env bash
name='autoconf'
release='3'
version='2.73'
url='https://www.gnu.org/software/autoconf/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/autoconf/autoconf-${version}.tar.xz")
depends=(perl m4)
makedepends=(help2man)
group=(sys.devel)
sha256sums=('9fd672b1c8425fac2fa67fa0477b990987268b90ff36d5f016dae57be0d6b52e')
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # empty makeinfo
    echo "#!/bin/sh" > ~/makeinfo
    chmod 755 ~/makeinfo
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

