#!/usr/bin/env bash
name='kinfocenter'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='A utility that provides information about a computer system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kinfocenter-${version}.tar.xz")
depends=(kauth kcmutils kconfig kcoreaddons kdeclarative ki18n kio kirigami kservice kwidgetsaddons libusb qt6-base
         qt6-declarative)
makedepends=(extra-cmake-modules solid kdoctools)
sha256sums=( 'df4ded29cb87d765b7d5f4b161c29a4255863844bee64247e6f0d3f0c8b3e5a3' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
    # systemsettings5 file is not part of kinfocenter
    rm -f $DESTDIR/usr/bin/kinfocenter
}
