#!/usr/bin/env bash
name='kdbusaddons'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtDBus'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdbusaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( '9ea3792b2f1c43d5551437260803fdd676c903e2768f4aac4186054e5b22d4ca' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


