#!/usr/bin/env bash
name='ostree'
release='6'
version='2026.1'
url='https://github.com/ostreedev/ostree'
description='Operating system and container binary deployment and upgrades'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/ostreedev/ostree/releases/download/v${version}/libostree-${version}.tar.xz")
depends=(fuse gpgme libarchive curl libsoup2 e2fsprogs libassuan)
makedepends=()
sha256sums=('8e77c285dd6fa5ec5fb063130390977be727fe11107335ed8778a40385069e95')
group=(dev.util)
uses=()
arch=('x86_64')

cd lib$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
	      --sysconfdir=/etc \
		    --localstatedir=/var \
    		--disable-glibtest \
        --with-soup \
        --without-libsystemd \
        --with-curl
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # move /usr/lib to /usr/lib64
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64
    rm -rf $DESTDIR/usr/lib/
    # remove garbage files
    rm -rvf $DESTDIR/etc/grub.d/
    rm -rvf $DESTDIR/lib/systemd
    rm -rvf $DESTDIR/usr/libexec/libostree/grub2-*

}

