#!/usr/bin/env bash
name='kpipewire'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Components relating to pipewire use in Plasma'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kpipewire-${version}.tar.xz")
depends=(ki18n kcoreaddons libdrm libva mesa pipewire libepoxy ffmpeg qt6-base qt6-declarative)
makedepends=(extra-cmake-modules plasma-wayland-protocols)
sha256sums=( 'dbf839b779c508c2020bdf9d642762387cba85059291deab38e8a0c15223badb' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

