#!/usr/bin/env bash
name='kde-gtk-config'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='GTK2 and GTK3 Configurator for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kde-gtk-config-${version}.tar.xz")
depends=(qt6-svg kdecoration kconfigwidgets kdbusaddons kwindowsystem)
makedepends=(extra-cmake-modules gtk3 sassc)
sha256sums=( 'd96e58214c6632b491d32caa4aeb15ae284f83e8a75d3bb9485978f42af4abd9' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
