#!/usr/bin/env bash
name='linux-tools'
release='3'
version='7.0.5'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=(eudev libcap libnl llvm openssl pciutils)
makedepends=(mklinux)
sha256sums=()
uses=()
arch=('x86_64')
group=(sys.kernel)

prepare(){
    wget https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-$version.tar.xz -O - | tar -xJvf -
}


package(){
    # install kernel (archlinux kernel config used)
    ALLOWROOT=1 bash mklinux -n -u -o "$DESTDIR" -t local -b linux-$version \
     -c "https://gitlab.archlinux.org/archlinux/packaging/packages/linux-hardened/-/raw/main/config"  \
     -v $version -y 1
}

