#!/usr/bin/env bash
name='kbookmarks'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Support for bookmarks and the XBEL format'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kbookmarks-${version}.tar.xz")
depends=(kconfig kconfigwidgets kcoreaddons kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( '75a43775ef03cb0c577c70d9605203789b3c75b786efa17a2e8c286d0c55fb93' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

