#!/usr/bin/env bash
name='kconfigwidgets'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Widgets for KConfig'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kconfigwidgets-${version}.tar.xz")
depends=(qt6-base kcodecs kconfig ki18n kwidgetsaddons kcoreaddons kguiaddons kcolorscheme)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( '404ed0606dfb13cc44c36deaf5f880eeec75018ae878125dabf83f32efeb0a7f' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
