#!/usr/bin/env bash
name='py3-markupsafe'
release='4'
version='3.0.3'
url='https://pypi.org/project/MarkupSafe'
description='Safely add untrusted strings to HTML/XML markup.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pallets/markupsafe/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('f1d9d06c34515dd3ad210ec769da613057b536d11d6c039183b87757a883a254')
group=(dev.python)
uses=()
arch=('x86_64')

cd markupsafe-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

