#!/usr/bin/env bash
name='kwin-x11'
release='7'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='An easy to use, but flexible, X Window Manager'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwin-x11-${version}.tar.xz")
depends=(kauth kcmutils kconfig kcoreaddons kcrash kdecoration kglobalaccel kguiaddons
         ki18n knewstuff kpackage kscreenlocker kservice ksvg kwidgetsaddons kwindowsystem
         lcms2 libSM libXext libXi libcanberra libdrm libepoxy libqaccessibilityclient
         libxcb libxkbcommon mesa plasma-activities qt6-base qt6-declarative qt6-sensors
         qt6-svg qt6-tools wayland xcb-util-cursor xcb-util-wm)
makedepends=(extra-cmake-modules)
sha256sums=( '9ac0b85b59016dfb91587f8c1970fbd5c6f215d12c9a419acd0bf7d0f0493606' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {

  cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
