#!/usr/bin/env bash
name='glibmm'
release='2'
version='2.86.0'
url='https://www.gtkmm.org'
description='C++ bindings for GLib'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/glibmm/${version%.*}/glibmm-${version}.tar.xz")
depends=(glib libsigc++)
makedepends=()
sha256sums=('39c0e9f6da046d679390774efdb9ad564436236736dc2f7825e614b2d4087826')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version
export PATH=$HOME:$PATH

prepare () {
    ln -s /bin/true $HOME/dot
}

setup () {
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}


