#!/usr/bin/env bash
name='xfsprogs'
release='6'
version='6.18.0'
url='https://xfs.wiki.kernel.org/'
description='XFS filesystem utilities'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-${version}.tar.xz")
depends=(inih liburcu icu)
makedepends=()
sha256sums=('3a6dc7b1245ce9bccd197bab00691f1b190bd3694d3ccc301d21b83afc133199')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-$version
setup(){
    make configure
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sbindir=/usr/sbin

}

build(){
    make $jobs
}

package(){
   # make install $jobs
  make DIST_ROOT="${DESTDIR}" PKG_ROOT_SBIN_DIR="/usr/sbin" install install-dev

}

