#!/usr/bin/env bash
name='wayland-protocols'
release='8'
version='1.47'
url='https://gitlab.freedesktop.org/wayland/wayland-protocols'
description='Wayland protocol files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$version/downloads/wayland-protocols-$version.tar.xz")
depends=(wayland)
makedepends=()
sha256sums=('5fd4349bcbc9bab9a46f8cf77d1f434296a7a052c87440a094f63fcf62a58e20')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        -Ddefault_library=both
}

build(){
    ninja -C build ${jobs}
}

package(){
    ninja -C build install
}

