#!/usr/bin/env bash
name='wayland-protocols'
release='9'
version='1.48'
url='https://gitlab.freedesktop.org/wayland/wayland-protocols'
description='Wayland protocol files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$version/downloads/wayland-protocols-$version.tar.xz")
depends=(wayland)
makedepends=()
sha256sums=('398036ac0eb6484982ddbde7ff86848d753231f9cdeeae983f06b52946625aa1')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        -Ddefault_library=both
}

build(){
    ninja -C build ${jobs}
}

package(){
    ninja -C build install
}

