#!/usr/bin/env bash
name='kcodecs'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Provide a collection of methods to manipulate strings using various encodings'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcodecs-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools gperf)
sha256sums=( '77f51f7586e8b457534d95dd241280e8b7475915c656e661dc37b1e8a773c595' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

