#!/usr/bin/env bash
name='libbytesize'
release='3'
version='2.12'
url='https://github.com/storaged-project/libbytesize'
description='A tiny library providing a C "class" for working with arbitrary big sizes in bytes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/storaged-project/libbytesize/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('e8b39afc6580f5777c9b1c8488e21fcbb60a3effdac7399eef0236185639bc41')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3
}

