#!/usr/bin/env bash
name='ki18n'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Advanced internationalization framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ki18n-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(doxygen extra-cmake-modules python)
sha256sums=( 'cd812ae95b0e95b40e46a50b9dea6d188eec001be96b1e1a5d962730e5f9bc58' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

