#!/usr/bin/env bash
name='kparts'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Document centric plugin system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kparts-${version}.tar.xz")
depends=(kconfig kcoreaddons ki18n kio kwidgetsaddons kxmlgui qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools)
sha256sums=( '0c2ce39f110e12ff0882c725bee7455b9085489c12d31eb4b3164b150fb8de24' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

