#!/usr/bin/env bash
name='glib'
release='7'
version='2.88.1'
_version='2.88'
url='https://download.gnome.org/sources/glib/'
description='Low-level core library that forms the basis for projects such as GTK+ and GNOME.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://download.gnome.org/sources/glib/${_version}/glib-${version}.tar.xz"
        "glib.sysconf")
depends=(libffi util-linux libpcre2 zlib)
makedepends=( )
sha256sums=('51ab804c56f6eab3e5045c774d1290ac5e4c923d4f9a3d8e33123bee45c1840e'
         'SKIP')
uses=()
arch=('x86_64')
group=(dev.libs)

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -D glib_debug=disabled \
        -D selinux=disabled \
        -D sysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../glib.sysconf ${DESTDIR}/etc/sysconf.d/glib
}

