#!/usr/bin/env bash
name='glib'
release='6'
version='2.87.0'
_version='2.87'
url='https://download.gnome.org/sources/glib/'
description='Low-level core library that forms the basis for projects such as GTK+ and GNOME.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://download.gnome.org/sources/glib/${_version}/glib-${version}.tar.xz"
        "glib.sysconf")
depends=(libffi util-linux libpcre2 zlib)
makedepends=( )
sha256sums=('926cf73d8eb90ea341cc2d6fc7b258901e1a086a3808b166b4476d69a98b2401'
         'SKIP')
uses=()
arch=('x86_64')
group=(dev.libs)

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -D glib_debug=disabled \
        -D selinux=disabled \
        -D sysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../glib.sysconf ${DESTDIR}/etc/sysconf.d/glib
}

