#!/usr/bin/env bash
name='kdeclarative'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Provides integration of QML and KDE Frameworks'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdeclarative-${version}.tar.xz")
depends=(ki18n kconfig kwidgetsaddons kguiaddons kglobalaccel qt6-base qt6-declarative)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( 'b14e81143aed25ee62413f9c2b3742c558f5b6a1da6c5b92ca9a95bb6341e964' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

