#!/usr/bin/env bash
name='chrpath'
release='3'
version='0.18'
url='https://directory.fsf.org/wiki/Chrpath'
description='Chrpath can modify the rpath and runpath of ELF executables'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://codeberg.org/pere/chrpath/archive/release-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('f09c49f0618660ca11fc6d9580ddde904c7224d4c6d0f6f2d1f9bcdc9102c9aa')
group=(app.admin)
uses=()
arch=('x86_64')

cd $name

setup(){
   autoreconf -vfi
   ./configure --prefix=/usr \
       --mandir=/usr/share/man
}

build(){
    make $jobs
}

package(){
    make docdir=/usr/share/doc/chrpath install

}

