#!/usr/bin/env bash
name='glslang'
release='5'
version='1.4.341.0'
url='https://github.com/KhronosGroup/glslang'
description='OpenGL and OpenGL ES shader front end and validator'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/glslang/archive/refs/tags/vulkan-sdk-$version.tar.gz")
depends=(gcc)
makedepends=()
sha256sums=('18cdf7d40a39001dde842c6a1338b2c9321ac5e487139b9d52b4b9c666da3c86')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-vulkan-sdk-$version

export CXXFLAGS+=" -ffat-lto-objects"

setup(){
    cmake \
      -Bbuild-shared \
      -GNinja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=None \
      -DALLOW_EXTERNAL_SPIRV_TOOLS=YES \
      -DBUILD_SHARED_LIBS=ON
    cmake \
      -Bbuild-static \
      -GNinja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=None \
      -DALLOW_EXTERNAL_SPIRV_TOOLS=YES \
      -DBUILD_SHARED_LIBS=OFF
}

build(){
    ninja -Cbuild-shared
    ninja -Cbuild-static
}

package(){
    ninja -Cbuild-shared install
    ninja -Cbuild-static install
    cd "${DESTDIR}"/usr/lib64
    for lib in *.so; do
      ln -sf "${lib}" "${lib}.0"
    done
}

