#!/usr/bin/env bash
name='kdoctools'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Documentation generation from docbook'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdoctools-${version}.tar.xz")
depends=(docbook-xml docbook-xsl karchive)
makedepends=(karchive ki18n libxml2 libxslt qt6-base perl-uri)
sha256sums=( '69026ef8607cb6257e4d1f0e46e451130ef7ba67994a83e4f9a6c46eefd5a3f3' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

#HATA : CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
#  Could NOT find PerlModules (missing: PerlModules_all_modules_found  URI::Escape)


setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

