#!/usr/bin/env bash
name='less'
release='5'
version='685'
url='https://ftp.gnu.org/gnu/less'
description='Excellent text file viewer'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/less/less-$version.tar.gz")
depends=(ncurses)
makedepends=()
sha256sums=('2701041e767e697ee420ce0825641cedc8f20b51576abe99d92c1666d332e9dc')
uses=(pcre2)
pcre2_depends=(libpcre2)
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        $(use_opt pcre2 "--with-regex=pcre2" "--without-pcre2")
}

build(){
    make
}

package(){
    make DESTDIR=${DESTDIR} install
}

