#!/usr/bin/env bash
name='libXaw3d'
release='2'
version='1.6.6'
url='https://gitlab.freedesktop.org/xorg/lib/libXaw3d'
description='X.Org Xaw3d library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXaw3d-$version.tar.gz")
depends=(libX11 libXt libXmu libXext)
makedepends=()
sha256sums=('0cdb8f51c390b0f9f5bec74454e53b15b6b815bc280f6b7c969400c9ef595803')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

