#!/usr/bin/env bash
name='kfind'
release='6'
version='26.04.2'
url='https://www.kde.org/applications/utilities/kfind'
description='Find Files/Folders'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/kfind-${version}.tar.xz")
depends=(karchive kcompletion kconfig kconfigwidgets kcoreaddons kfilemetadata ki18n kio kwidgetsaddons
         kxmlgui qt6-5compat qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( '2902110890a9dd96a017e71fae9b0c28ae53c946b977f3ff5f53b30e8932b553' )
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
