#!/usr/bin/env bash
name='py3-packaging'
release='5'
version='26.2'
url='https://pypi.org/project/packaging'
description='Core utilities for Python3 packages'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('Apache-2.0 AND BSD-2-Clause')
source=("https://github.com/pypa/packaging/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer)
sha256sums=('24d24b249ba8fb0213ac046d8e2c1cecf6b1013311a5febfb87a02093ef2c991')
group=(dev.python)
uses=()
arch=('x86_64')

cd "packaging"-$version

export PYTHONPATH=src/packaging

## this package require itself. so we must use venv for build
prepare(){
    python3 -m venv .
    source bin/activate
    pip3 install build installer flit
}


build(){
    source bin/activate
    python -m build -nw
}

package(){
    python -m installer --destdir="$DESTDIR" dist/*.whl
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3

}

