#!/usr/bin/env bash
name='libxss'
release='3'
version='1.2.5'
url='https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver'
description='X11 Screen Saver extension library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
#source=("https://salsa.debian.org/xorg-team/lib/libxss/-/archive/libxss-${version}/libxss-#libxss-${version}.tar.gz")
source=("https://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-${version}.tar.xz")
depends=(libXext util-macros xorgproto)
makedepends=()
sha256sums=('5057365f847253e0e275871441e10ff7846c8322a5d88e1e187d326de1cd8d00')
group=(x11.libs)
uses=()
arch=('x86_64')

cd "libXScrnSaver"-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

