#!/usr/bin/env bash
name='grim'
release='2'
version='1.5.0'
url='https://git.sr.ht/~emersion/grim'
description='Grabs images from Wayland compositors'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/emersion/grim/-/archive/v$version/grim-v$version.tar.gz")
depends=(wayland libpng libjpeg-turbo)
makedepends=(meson)
sha256sums=('9e72a98f7621b1f5741b405b8dbd447acf7d300ddb12667ec526db1ce6154eaa')
group=(gui.apps)
uses=()
arch=('x86_64')

cd $name-v$version

setup () {
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

