#!/usr/bin/env bash
name='qt6-websockets'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Provides WebSocket communication compliant with RFC 6455'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebsockets-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake)
sha256sums=('243e3aa11924c8c5c1645e892f62d013caa3766c57512ca926d5b58146646fbf')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebsockets-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}