#!/usr/bin/env bash
name='kmenuedit'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='KDE menu editor'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kmenuedit-${version}.tar.xz")
depends=(kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'f27fed5c8989ad00adc714bc7f377adfca9742c4ccd3afff9478d502eeafffab' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

