#!/usr/bin/env bash
name='gobject-introspection'
release='6'
version='1.86.0'
url='https://gitlab.gnome.org/GNOME/gobject-introspection.git/'
description='Introspection system for GObject-based libraries '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/${version}/gobject-introspection-${version}.tar.gz")
depends=(glib)
makedepends=()
sha256sums=('eadae02135e96ad40221b4a9eb5e168f8c70ef3f697485c38345a3638adf51a2')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    sed -i "s|subdir('tests')||g" meson.build
}

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

