#!/usr/bin/env bash
name='qt6-scxml'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Static and runtime integration of SCXML models into Qt code'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtscxml-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('8e495245e5d1fe75de612c8a07e4043635407a1979bb1dd588f1751d1390203f')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtscxml-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}