#!/usr/bin/env bash
name='ktexteditor'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Advanced embeddable text editor'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ktexteditor-${version}.tar.xz")
depends=(karchive kauth kcodecs kcolorscheme kcompletion kconfig kconfigwidgets kcoreaddons kguiaddons ki18n kio kitemviews kparts ktextwidgets kwidgetsaddons kxmlgui sonnet syntax-highlighting qt6-base qt6-speech qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( '2b737a61737e73650cd0b40d9e246a182dcccc6c8ae8121cfcb9415433ee41ae' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

