#!/usr/bin/env bash
name='vulkan-headers'
release='4'
version='1.4.347'
url='https://github.com/KhronosGroup/Vulkan-Headers'
description='Vulkan Header files and API registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('6611f09ed95aaf2c47ad76df9fb3e5455ce52d1ed3d0ef5dbc0d63e3208d3faa')
group=(dev.util)
uses=()
arch=('x86_64')

cd Vulkan-Headers-$version

setup(){
    mkdir build && cd build
    cmake -G Ninja .. \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

