#!/usr/bin/env bash
name='sord'
release='2'
version='0.16.22'
url='https://drobilla.net/software/sord.html'
description='Library for storing RDF data in memory '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.drobilla.net/sord-$version.tar.xz")
depends=(lv2)
makedepends=()
sha256sums=('bb23b34b216579136795d518cffa73d91cf205594ce9accebfd408afb839173f')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ -Db_lto=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

