#!/usr/bin/env bash
name='gsettings-desktop-schemas'
release='4'
version='49.1'
url='https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git/'
description=' Collection of GSettings schemas for GNOME desktop '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$version/gsettings-desktop-schemas-$version.tar.gz")
depends=()
makedepends=(gobject-introspection meson)
sha256sums=('c6baabe8c2c8b56825d0cfcc2ef859e5878a9de100be2894342640c094334517')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

