#!/usr/bin/env bash
name='gdk-pixbuf'
release='2'
version='2.44.7'
url='https://gitlab.gnome.org/GNOME/gdk-pixbuf'
description='gdk-pixbuf Image loading library for GTK+ '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/gdk-pixbuf/${version%.*}/gdk-pixbuf-$version.tar.xz"
        "gdk-pixbuf.sysconf")
depends=(libjpeg-turbo shared-mime-info gi-docgen libtiff libpng)
makedepends=()
sha256sums=('172f80e3626ec31520a970400f1a3694e04718f6c2cd2885f75250fb5a6995a4'
         'SKIP')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false \
        -D installed_tests=false \
        -D tiff=enabled \
        -D glycin=disabled \
        -D tests=false

}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../gdk-pixbuf.sysconf ${DESTDIR}/etc/sysconf.d/gdk-pixbuf
}

