#!/usr/bin/env bash
name='serd'
release='3'
version='0.32.8'
url='https://drobilla.net/software/serd.html'
description='Library for RDF syntax which supports reading and writing Turtle and NTriples '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/drobilla/serd/archive/refs/tags/v$version.tar.gz")
depends=(lv2)
makedepends=()
sha256sums=('057cb46d2dee09cfa91727c6835341811c1789e8f06d4372f2ffbfe36924ffb4')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddocs=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

