#!/usr/bin/env bash
name='bubblewrap'
release='4'
version='0.12.0'
url='https://containers/bubblewrap'
description='Unprivileged sandboxing tool, namespaces-powered chroot-like solution'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/containers/bubblewrap/archive/refs/tags/v$version.tar.gz")
depends=(libcap)
makedepends=()
sha256sums=('3f66d9e3f85396f6d7d7fbd2859f277e4fd3a9303341bfe2ff325251bda65fd4')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja install -C build $jobs
}

