#!/usr/bin/env bash
name='kwindowsystem'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Access to the windowing system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwindowsystem-${version}.tar.xz")
depends=(libX11 libxcb qt6-base qt6-wayland wayland xcb-util-keysyms libXfixes libSM libXext qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-declarative wayland-protocols)
sha256sums=( '401e5700ab36530a605410464268bf726c898da42c6f7d7bf05a9db00ccfe172' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


