#!/usr/bin/env bash
name='patch'
release='2'
version='2.8'
url='https://ftp.gnu.org/gnu/patch/'
description='A utility to apply patch files to original sources'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/patch/patch-$version.tar.xz")
depends=(attr)
makedepends=()
sha256sums=('f87cee69eec2b4fcbf60a396b030ad6aa3415f192aa5f7ee84cad5e11f7f5ae3')
uses=()
group=(sys.devel)
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

