#!/usr/bin/env bash
name='libXdmcp'
release='2'
version='1.1.5'
url='X.Org X Display Manager Control Protocol library'
description='X.Org X Display Manager Control Protocol library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXdmcp-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('d8a5222828c3adab70adf69a5583f1d32eb5ece04304f7f8392b6a353aa2228c')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

