#!/usr/bin/env bash
name='py3-dbus'
_name='dbus-python'
release='3'
version='1.4.0'
url='https://www.freedesktop.org/wiki/Software/DBusBindings'
description='Python3 bindings for DBUS'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://gitlab.freedesktop.org/dbus/dbus-python/-/archive/dbus-python-$version/dbus-python-dbus-python-$version.tar.gz")
depends=(python dbus)
makedepends=(py3-sphinx py3-tomli)
sha256sums=('da4ee9bbb9eb901d463a7cc9f99dfdbe6c751c8b48b29b78d378985a3c9656ad')
group=(dev.python)
uses=()
arch=('x86_64')

cd $_name-$_name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

