#!/usr/bin/env bash
name='powerdevil'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Manages the power consumption settings of a Plasma Shell'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/powerdevil-${version}.tar.xz")
depends=(plasma-activities kauth kcmutils kconfig kcoreaddons kcrash kdbusaddons kglobalaccel ki18n
         kidletime kirigami kitemmodels knotifications ksvg kwindowsystem kxmlgui layer-shell-qt libkscreen
         libplasma libxcb plasma-workspace qt6-base qt6-declarative solid
)
makedepends=(extra-cmake-modules kdoctools kcmutils)
sha256sums=( '7635efffd503e78d92bcc03033d5681e51577ec92bc6da72f2ab2828bb0a34db' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


