#!/usr/bin/env bash
name='xorgproto'
release='5'
version='2025.1'
url='https://gitlab.freedesktop.org/xorg/proto/xorgproto'
description='X.Org combined protocol headers'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/proto/xorgproto-${version}.tar.xz")
depends=()
makedepends=(util-macros)
sha256sums=('56898c716c0578df8a2d828c9c3e5c528277705c0484381a81960fe1a67668e8')
uses=()
arch=('x86_64')
group=(x11.base)

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --without-xmlto \
        --without-xsltproc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
