#!/usr/bin/env bash
name='qt6-httpserver'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Qt6 HTTP Server'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qthttpserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('04bf70fcf76861f9b6870c728085f2375a6b6d923cb5d1a116dff2ed52a4e706')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qthttpserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
