#!/usr/bin/env bash
name='karchive'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Qt addon providing access to numerous types of archives'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/karchive-${version}.tar.xz")
depends=(qt6-base bzip2 openssl xz-utils)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( '434edf78df8f4c9f25000d107ad1520d7ac14db580a202047bf19cbf77376522' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DWITH_LIBZSTD=OFF

}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

