#!/usr/bin/env bash
name='kquickcharts'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick plugin providing high-performance charts'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kquickcharts-${version}.tar.xz")
depends=(kirigami qt6-base qt6-declarative)
makedepends=(extra-cmake-modules qt6-shadertools)
sha256sums=( 'd2a533bbf3d7f257e9306009bc32bdea41346cbd8e82d06c188879d5f0460380' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
