#!/usr/bin/env bash
name='xinit'
release='2'
version='1.4.4'
url='https://gitlab.freedesktop.org/xorg/app/xinit'
description='X Window System initializer xinit'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/xinit/-/archive/xinit-$version/xinit-xinit-$version.tar.gz"
        "files/xinitrc"
        "files/xserverrc"
        "files/Xsession"
        "files/xinit.sysconf"
        "files/xinit.confd"
        "files/xinit.initd"
        "files/Xresources"
        "files/65-dontvtswitch.conf"
)
depends=(util-macros xorgproto libX11 xorg-server xterm xhost xrdb)
makedepends=()
sha256sums=('a0efb773acea51c35e1295bfc1ac957ddf1edede9f76c20929e9c13b0644eb7a'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        -sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install $jobs
    install -m755 -D ../xinitrc "$DESTDIR"/etc/X11/xinit/xinitrc
    install -m755 -D ../Xsession "$DESTDIR"/etc/X11/xinit/Xsession
    install -m755 ../xserverrc "$DESTDIR"/etc/X11/xinit/xserverrc
    install -m755 -D ../xinit.sysconf "$DESTDIR"/etc/sysconf.d/xinit
    install -m755 -D ../xinit.initd "$DESTDIR"/etc/init.d/xinit
    install -m755 -D ../xinit.confd "$DESTDIR"/etc/conf.d/xinit
    install -m644 -D ../65-dontvtswitch.conf "$DESTDIR"/usr/share/X11/xorg.conf.d/65-dontvtswitch.conf
    install ../Xresources "$DESTDIR"/etc/X11/Xresources
    # allow local connections config
    mkdir -p "$DESTDIR"/etc/X11/xinit/xinitrc.d
    echo "#!/bin/sh" > "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
    echo "xhost +local:" >> "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
    chmod 754 "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
}

