#!/usr/bin/env bash
name='knewstuff'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Support for downloading application assets from the network'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knewstuff-${version}.tar.xz")
depends=(qt6-base karchive kconfig kcoreaddons ki18n kpackage attica kwidgetsaddons syndication)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=( '8c19df7ba5940c36ff15051703acd3a16c664b4a570817b6770fafc7ab59d6de' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


