#!/usr/bin/env bash
name='libXfont2'
release='2'
version='2.0.7'
url='https://gitlab.freedesktop.org/xorg/lib/libXfont.git/'
description='X.Org Xfont library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXfont2-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('8b7b82fdeba48769b69433e8e3fbb984a5f6bf368b0d5f47abeec49de3e58efb')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

