#!/usr/bin/env bash
name='mkinitrd'
release='11'
version='1.0.2'
url='https://gitlab.com/turkman/devel/sources/mkinitrd'
description='Initial ramdisk system from turkman linux'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mkinitrd/-/archive/$version/mkinitrd-$version.tar.gz"
        "mkinitrd.sysconf")
depends=(findutils coreutils)
makedepends=()
sha256sums=('51d882b0ec354a813d6cffc6bef698268efefa447e5b351465a531841bc2e1f3'
            'SKIP')
uses=()
group=(sys.kernel)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr
}

package(){
    ninja -C build install
    # sysconf trigger
    mkdir -p $DESTDIR/etc/sysconf.d
    install ../mkinitrd.sysconf $DESTDIR/etc/sysconf.d/mkinitrd
}
