#!/usr/bin/env bash
name='mkinitrd'
release='10'
version='1.0.1'
url='https://gitlab.com/turkman/devel/sources/mkinitrd'
description='Initial ramdisk system from turkman linux'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mkinitrd/-/archive/$version/mkinitrd-$version.tar.gz"
        "mkinitrd.sysconf")
depends=(findutils coreutils)
makedepends=()
sha256sums=('1f1f152ff7928fc382065091e13f4fdb4eea43cd3b63266c1ca7cbf396f7027f'
            'SKIP')
uses=()
group=(sys.kernel)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr
}

package(){
    ninja -C build install
    # sysconf trigger
    mkdir -p $DESTDIR/etc/sysconf.d
    install ../mkinitrd.sysconf $DESTDIR/etc/sysconf.d/mkinitrd
}
