#!/usr/bin/env bash
name='kconfig'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Configuration system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kconfig-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( 'e19728b80e6cc017502fcb50fe6d7e9b5ba9727871ac3a4e9811875e01cb5fe9' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

