#!/usr/bin/env bash
name='py3-cerberus'
release='4'
version='1.3.8'
url='http://python-cerberus.org/'
description='Lightweight, extensible data validation library for Python'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('ISC')
source=("https://github.com/pyeve/cerberus/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-setuptools py3-build py3-installer py3-wheel)
sha256sums=('3eb480747f6b6dc6e3e6854f8388d03a2269a8fa18429b3e4a01aee01706fb03')
group=(dev.python)
uses=()
arch=('x86_64')

cd "cerberus"-$version

build(){
    python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3

}


