#!/usr/bin/env bash
name='gtkmm3'
release='3'
version='3.24.10'
url='https://www.gtkmm.org/'
description='C++ bindings for GTK+ 3'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/gtkmm/${version%.*}/gtkmm-${version}.tar.xz")
depends=(atkmm cairomm glibmm pangomm)
makedepends=(mm-common)
sha256sums=('7ab7e2266808716e26c39924ace1fb46da86c17ef39d989624c42314b32b5a76')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd "gtkmm"-$version


unset  meson
setup () {
	#autoreconf -fvi
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

