#!/usr/bin/env bash
name='nasm'
release='2'
version='3.01'
url='https://github.com/netwide-assembler/nasm'
description='80x86 assembler designed for portability and modularity'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/netwide-assembler/nasm/archive/refs/tags/nasm-$version.tar.gz")
depends=(zlib)
makedepends=(diffutils asciidoc xmlto)
sha256sums=('af2f241ecc061205d73ba4f781f075d025dabaeab020b676b7db144bf7015d6d')
group=(dev.lang)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    ./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
    # do not build doc
    touch nasm.1
    touch ndisasm.1
}

package(){
    make install $jobs
    install -Dm 644 LICENSE -t "${DESTDIR}"/usr/share/licenses/nasm
    rm -rf $DESTDIR/usr/share/man
}

