#!/usr/bin/env bash
name='pangomm'
release='2'
version='2.56.1'
url='https://www.gtkmm.org/'
description='C++ bindings for Pango'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/pangomm/${version%.*}/pangomm-${version}.tar.xz")
depends=()
makedepends=()
sha256sums=('539f5aa60e9bdc6b955bb448e2a62cc14562744df690258040fbb74bf885755d')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

