#!/usr/bin/env bash
name='kded'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Extensible deamon for providing system level services'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kded-${version}.tar.xz")
depends=(kconfig kservice kcrash kcoreaddons kdbusaddons qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=( '4f24067915b05a1d0cc87e2c37f37eb0e8c441e8fccdf06ca27ee7b923058243' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd
}
