#!/usr/bin/env bash
name='networkmanager-qt'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for NetworkManager API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/networkmanager-qt-${version}.tar.xz")
depends=(networkmanager qt6-base )
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( 'a8193895b420d576fac228388ba8fd1b24d6f229c43b7963e2ed581ef82cad9a' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

