#!/usr/bin/env bash
name='sway'
release='6'
version='1.11'
bg_version='1.2.2'
url='https://github.com/swaywm/sway'
description=='i3-compatible Wayland window manager'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/swaywm/sway/archive/refs/tags/$version.zip"
        "https://github.com/swaywm/swaybg/archive/refs/tags/v${bg_version}.tar.gz"
        "sway.desktop")
depends=(wlroots json-c gdk-pixbuf cairo libevdev libinput pango vulkan-loader xcb-util-renderutil)
makedepends=()
sha256sums=('c4a86c3c4aef3c0f91635b983d7e0f27c3925c09092825dcc75f648cab640d65'
            '94e5c06a765d969e554b0f321f9cdf9c283a3fdaf70ad4e3d28163b21bd4d240'
            'SKIP')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dwerror=false \
        -Dtray=enabled
    cd ..
    cd swaybg-${bg_version}
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dgdk-pixbuf=enabled
}

build(){
    ninja -C build
    ninja -C ../swaybg-${bg_version}/build
}

package(){
    ninja -C build install
    ninja -C ../swaybg-${bg_version}/build install
    install -D -m644 ../sway.desktop \
		    -t "$DESTDIR"/usr/share/wayland-sessions/
}

