#!/usr/bin/env bash
name='libksysguard'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='KDE system monitor library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/libksysguard-$version.tar.xz")
depends=(kauth kconfig kcoreaddons kdeclarative ki18n kirigami kitemmodels knewstuff kpackage kquickcharts kservice
         libnl libpcap qt6-base qt6-declarative solid zlib lm-sensors)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=( 'e34c01438399fc23090cde4d47225bcd8f60899d138ecae99cc599659536ace3' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

