#!/usr/bin/env bash
name='kpeople'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='A library that provides access to all contacts and the people who hold them'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpeople-${version}.tar.xz")
depends=(kcontacts kcoreaddons ki18n kwidgetsaddons kitemviews qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=( '586407310370f9a7fe88773c90e83e227bec7f5f6f860df6540d69db425581d6' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
