#!/usr/bin/env bash
name='diffutils'
release='3'
version='3.12'
url='https://ftp.gnu.org/gnu/diffutils/'
description='Utility programs used for creating patch files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/diffutils/diffutils-$version.tar.xz")
depends=(bash)
makedepends=()
sha256sums=('7c8b7f9fc8609141fdea9cece85249d308624391ff61dedaf528fcb337727dfd')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

prepare(){
    > ~/makeinfo
    chmod 755 ~/makeinfo
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

