#!/usr/bin/env bash
name='kwayland'
release='6'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Qt-style Client and Server library wrapper for the Wayland libraries'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/kwayland-${version}.tar.xz")
#source=("https://download.kde.org/stable/frameworks/${version%.*}/kwayland-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland)
makedepends=(extra-cmake-modules doxygen qt6-tools wayland-protocols plasma-wayland-protocols)
sha256sums=( '8621d17e9100be60ea340235208d044fd02931dbef76a32d9a477de31c8e33f4' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
