#!/usr/bin/env bash
name='gpgme'
release='6'
version='2.1.0'
url='https://www.gnupg.org/ftp/gcrypt/gpgme'
description='gnupg made easy'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-$version.tar.bz2")
depends=(gnupg)
makedepends=()
sha256sums=('841c5ea53fc26259f4fbf0e8bde982dea1b8a1ca0cb77e681c82b050566bf92b')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    > ~/makeinfo
    chmod +x ~/makeinfo
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
    ln -s libgpgme.so $DESTDIR/usr/lib64/libgpgme.so.11
}

