#!/usr/bin/env bash
name='gpgme'
release='5'
version='2.0.1'
url='https://www.gnupg.org/ftp/gcrypt/gpgme'
description='gnupg made easy'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-$version.tar.bz2")
depends=(gnupg)
makedepends=()
sha256sums=('821ab0695c842eab51752a81980c92b0410c7eadd04103f791d5d2a526784966')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    > ~/makeinfo
    chmod +x ~/makeinfo
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
    ln -s libgpgme.so $DESTDIR/usr/lib64/libgpgme.so.11
}

