#!/usr/bin/env bash
name='libnvme'
release='6'
version='1.16.1'
url='https://example.org'
description='C Library for NVM Express on Linux'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linux-nvme/libnvme/archive/refs/tags/v${version}/libnvme-${version}.tar.gz")
depends=(json-c openssl linux-headers)
makedepends=(dbus	meson python util-linux)
sha256sums=('ce1d9d393feb84c4e82ca096db2bdb7dd4a5fd1997d711cc1904796944f2c579')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Ddefault_library=both
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}

