#!/usr/bin/env bash
name='muffin'
release='6'
version='6.6.3'
url='https://github.com/linuxmint/muffin'
description='Cinnamon window manager based on Mutter'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/muffin/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop gobject-introspection libcanberra libinput
         libSM libxkbcommon startup-notification zenity graphene pipewire
         xorg-xwayland)
makedepends=(meson intltool gobject-introspection wayland-protocols)
sha256sums=('af1aa8e68699895a841415c007c7f3f48efc06f07c50d219d30f8131a981248e')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
