#!/usr/bin/env bash
name='muffin'
release='5'
version='6.6.0'
url='https://github.com/linuxmint/muffin'
description='Cinnamon window manager based on Mutter'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/muffin/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop gobject-introspection libcanberra libinput
         libSM libxkbcommon startup-notification zenity graphene pipewire
         xorg-xwayland)
makedepends=(meson intltool gobject-introspection wayland-protocols)
sha256sums=('f8cd088d39add3ee65011f0edd7e745f9b3f25154af47774a2baad1a7e0b1adf')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
