#!/usr/bin/env bash
name='libclc'
release='6'
version='22.1.0'
url='https://libclc.llvm.org/'
description='Open source implementation of the library requirements of the OpenCL C programming language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/llvm-project-$version.src.tar.xz")
depends=(spirv-llvm-translator)
makedepends=()
sha256sums=('25d2e2adc4356d758405dd885fcfd6447bce82a90eb78b6b87ce0934bd077173')
group=(dev.libs)
uses=()
arch=('x86_64')

cd llvm-project-$version.src

setup(){
    mkdir libclc/build
    cmake -S libclc -B libclc/build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    ninja -C libclc/build
}

package(){
    ninja -C libclc/build install
}

