#!/bin/bash
name=busybox
version=1.38.0
release=4
url='https://busybox.net'
description='BusyBox is a software suite that provides several Unix utilities in a single executable file.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
arch=(x86_64)
group=(sys.base)
makedepends=(musl)
source=("https://busybox.net/downloads/busybox-$version.tar.bz2"
        "files/busybox.sysconf"
        "files/udhcpc.openrc"
        "files/udhcpc.script"
)
sha256sums=("34f9ea6ff8636f2c9241153b9114eefa9e65674a45318ae1ef95bb5f31c53bb2"
         "SKIP"
         "SKIP"
         "SKIP"
         "SKIP"
)

export PATH=$PATH:/usr/bin/core_perl
cd $name-$version

export CFLAGS="-Wno-all -Os -s"
export LDFLAGS="-fno-link-libatomic"

prepare(){
    for tool in ar strip ld; do
        ln -s /usr/bin/$tool ../musl-$tool
    done
    sed -i 's|/home|/data/user|g' loginutils/adduser.c
}

setup(){
    make defconfig
    sed -i "s|.*CONFIG_STATIC_LIBGCC .*|CONFIG_STATIC_LIBGCC=y|" .config
    sed -i "s|CONFIG_TC=.*|# CONFIG_TC is not set|" .config
    sed -i "s|.*CONFIG_STATIC .*|CONFIG_STATIC=y|" .config
    sed -i 's|CONFIG_CROSS_COMPILER_PREFIX=.*|CONFIG_CROSS_COMPILER_PREFIX="musl-"|' .config

}

build(){
    make $jobs
}

package(){
    mkdir -p ${DESTDIR}/bin/ ${DESTDIR}/etc/sysconf.d ${DESTDIR}/usr/share/initramfs-tools/{hooks,conf-hooks.d}/
    install busybox ${DESTDIR}/bin/busybox
    install ../busybox.sysconf ${DESTDIR}/etc/sysconf.d/busybox
    # install udhcpc script and service
    mkdir -p ${DESTDIR}/usr/share/udhcpc/ ${DESTDIR}/etc/init.d/
    install ../udhcpc.script ${DESTDIR}/usr/share/udhcpc/default.script
    install ../udhcpc.openrc ${DESTDIR}/etc/init.d/udhcpc
}

