#!/usr/bin/env bash
name='accountsservice'
release='2'
version='26.27.3'
url='https://www.freedesktop.org/software/accountsservice/'
description='D-Bus interface for user account query and manipulation'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/accountsservice/accountsservice/-/archive/${version}/accountsservice-${version}.tar.gz")
#source=("https://www.freedesktop.org/software/accountsservice/accountsservice-${version}.tar.xz")
depends=(elogind glib polkit)
makedepends=(meson gobject-introspection)
sha256sums=('11de07bcd499c2277f78a6fc830d1437654f3397cc7bbed19c28b3818435ba38')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build \
        --prefix=/usr \
		    -Db_lto=true \
		    -Dsystemdsystemunitdir=no \
		    -Delogind=true \
		    -Dintrospection=true \
		    -Dlightdmconffile=/etc/lightdm/lightdm.conf \
		    -Ddocbook=false \
		    -Dgtk_doc=false \
		    -Dadmin_group=wheel \
		    -Dvapi=true
}

build () {
    ninja -C build
}

package () {
    ninja -C build install
}

