#!/usr/bin/env bash
name='labwc'
release='3'
version='0.9.5'
url='https://github.com/labwc/labwc'
description=='A Wayland window-stacking compositor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/labwc/labwc/archive/$version.tar.gz")
depends=(libpng libsfdo librsvg pango seatd wlroots wayland xorg-xwayland)
makedepends=()
sha256sums=('905af63ad24643a6f548b51107a05ac639d1707aaafdd18f656b55f7cfb28611')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

