#!/usr/bin/env bash
name='libpcre2'
release='2'
version='10.47'
url='https://pcre.org'
description='Perl-compatible regular expression library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('BSD')
source=("https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${version}/pcre2-${version}.tar.gz")
sha256sums=('c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16')
arch=('x86_64')
group=(dev.libs)
uses=(zlib bzip2)
zlib_depends=(zlib)
bzip2_depends=(bzip2)

cd pcre2-$version

setup(){
    ./configure --prefix=/usr \
    	--libdir=/usr/lib64 \
	    --enable-shared \
	    --enable-static \
        --enable-pcre2-16 \
        --enable-pcre2-32 \
        --enable-jit \
        --enable-pcre2test-libreadline \
	$(use_opt zlib --enable-pcre2grep-libz --disable-pcre2grep-libz) \
	$(use_opt bzip2 --enable-pcre2grep-libbz2 --disable-pcre2grep-libbz2)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

