#!/usr/bin/env bash
name='plasma-activities'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Core components for KDE Activities'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-${version}.tar.xz")
depends=(kconfig kcoreaddons qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools)
sha256sums=( '38ff957996a09c15236e93b035ba123480a58aff74894b61b7df1020ec442b59' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
