#!/usr/bin/env bash
name='libXdamage'
release='2'
version='1.1.7'
url='https://gitlab.freedesktop.org/xorg/lib/libXdamage.git/'
description='X.Org Xdamage library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXdamage-$version.tar.xz")
depends=(libXfixes libX11)
makedepends=()
sha256sums=('127067f521d3ee467b97bcb145aeba1078e2454d448e8748eb984d5b397bde24')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

