#!/bin/bash
name=base-files
release=6
version=$release
url='https://gitlab.com/turkmen-linux/devel/sources/base-files'
description='Base system files'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/base-files/-/archive/$version/base-files-$version.zip"
        "base-files.sysconf"
        "logo.svg"
        "os-release")
sha256sums=('593e990f2d388a0c365bbb2fe03b5b158afdc565af81393fe1524c52645cd358'
         'SKIP'
         'SKIP'
         'SKIP')
arch=(x86_64)
group=(sys.base)

cd "$name-$version"

package(){
    mkdir -p ${DESTDIR}/etc/sysconf.d \
        ${DESTDIR}/usr/share/icons/hicolor/scalable/apps/
    make install
    install ../base-files.sysconf  ${DESTDIR}/etc/sysconf.d/base-files
    install ../os-release  ${DESTDIR}/etc/
    install ../logo.svg ${DESTDIR}/usr/share/icons/hicolor/scalable/apps/turkmen.svg
}
