#!/usr/bin/env bash
name='py3-curl'
release='4'
version='8.19.0'
_version="271cb3e18ff81eada3d8d4df10fa0c511acae7e0"
url='http://pycurl.sourceforge.net/'
description='A Python 3.x interface to libcurl'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'MIT')
source=("https://salsa.debian.org/python-team/packages/pycurl/-/archive/upstream/${version}/pycurl-upstream-${version}.tar.gz")
depends=(python curl openssl)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('56cff5e12e19e630cd71c78242484156823f65cde9afad76369a86cb7992e19e')
group=(dev.python)
uses=()
arch=('x86_64')
cd "pycurl-upstream"-$_version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}


