#!/usr/bin/env bash
name='qt6-svg'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Classes for displaying the contents of SVG files'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsvg-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake)
sha256sums=('7f3cf02f4824bf03c2c5859ea6db173bf1482a1daf24e6cdf7bc78cfa26a8a94')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsvg-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}