#!/usr/bin/env bash
name='lilv'
release='2'
version='0.26.4'
url='https://drobilla.net/software/lilv.html'
description='Library to make the use of LV2 plugins as simple as possible for applications '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.drobilla.net/lilv-$version.tar.xz")
depends=(lv2 serd sord sratom zix)
makedepends=()
sha256sums=('1c8b5fcb78718173e67d76e51ad423f5113a9ff68463f2566195ae46396089e3')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

unset meson

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ -Ddocs=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3

}

