#!/usr/bin/env bash
name='libxcb'
release='3'
version='1.17.0'
url='https://xcb.freedesktop.org'
description='X C-language Bindings library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/lib/libxcb-$version.tar.xz")
depends=(libXau libXdmcp xcb-proto)
makedepends=(xorgproto util-macros python)
sha256sums=('599ebf9996710fea71622e6e184f3a8ad5b43d0e5fa8c4e407123c88a59a6d55')
uses=()
arch=('x86_64')
group=(x11.libs)

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-shared \
        --enable-static \
        --disable-devel-docs \
        --without-launchd \
        --without-doxygen
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

