#!/usr/bin/env bash
name='plasma-pa'
release='5'
version='6.7.0'
url='https://kde.org/plasma-desktop/'
description='Plasma applet for audio volume management using PulseAudio'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-pa-$version.tar.xz")
depends=(pulseaudio-qt pipewire plasma-workspace)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'badce8811107ee57720716275ac5fc12116689bc34ce493cabe7228e1b658f51' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

