#!/usr/bin/env bash
name='dconf'
release='2'
version='0.49.0'
url='https://gitlab.gnome.org/GNOME/dconf.git/'
description=' Simple low-level configuration system '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/dconf/${version%.*}/dconf-${version}.tar.xz")
depends=(dbus glib)
makedepends=()
sha256sums=('16a47e49a58156dbb96578e1708325299e4c19eea9be128d5bd12fd0963d6c36')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build $jobs install
}

