#!/usr/bin/env bash
name='qemu'
release='3'
version='10.0.2'
url='https://qemu.org'
description='Quick Emulator'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.qemu.org/qemu-$version.tar.xz"
        "https://codeberg.org/shakakibara12/qemu-anti-detection/raw/branch/main/qemu-$version.patch"
)
depends=(alsa-lib bzip2 curl cyrus-sasl eudev fuse glib
         gnutls jack2 keyutils libaio libcap-ng libpulse
         libseccomp libusb libxkbcommon mesa ndctl pam
         pipewire
)
makedepends=()
sha256sums=('ef786f2398cb5184600f69aef4d5d691efd44576a3cff4126d38d4c6fec87759'
            'f0ddc883ecf6ccf8e0deb257f2d3d04623bba536635e678e1d36468a3bdd8b59'
)
group=(app.emulation)
uses=(gtk vnc)
arch=('x86_64')

gtk_depends=(gtk3 vte3)


cd $name-$version

prepare(){
    patch -Np1 -i ../qemu-$version.patch
    cd ..
    cp -prf $name-$version $name-$version.static
}

setup () {

    opts=(
        --libdir=/usr/lib64/ \
        --disable-zstd \
    )
    # configure system
    ./configure --prefix=/usr \
        --disable-linux-user \
        --target-list=x86_64-softmmu,aarch64-softmmu \
        --enable-slirp \
        $(use_opt gtk --enable-gtk --disable-gtk) \
        $(use_opt vnc --enable-vnc --disable-vnc) \
        ${opts[@]}
    # configure user static
    cd ../$name-$version.static
    ./configure --prefix=/usr \
        --disable-system \
        --enable-linux-user \
        --static \
        --target-list=aarch64-linux-user,x86_64-linux-user \
        ${opts[@]}
}

build () {
    make -C ../$name-$version.static $jobs
    make $jobs
}

package () {
    make -C ../$name-$version.static install $jobs
    make install $jobs
}

