#!/usr/bin/env bash
name='qt6-languageserver'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Qt implementation of the Language Server Protocol'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtlanguageserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('50008537f2ca54abb3b8dc3f26759864e9cad2b2ad39e92e42fa718de2dd8aef')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtlanguageserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
