#!/usr/bin/env bash
name='xdg-desktop-portal-kde'
release='1'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='A backend implementation for xdg-desktop-portal using Qt/KF5'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/$name-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules)
sha256sums=( 'f5afc06f948b73b2a0103d9ee6e57744a9884a3f2e0810807776ec4bf7102ada' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
