#!/usr/bin/env bash
name='qt6-virtualkeyboard'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtvirtualkeyboard-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('a1c6967b326243b2ca8d50bc7b7f7852c3975d9aa6ce4b186ebdf35bb1007e1c')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtvirtualkeyboard-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}