#!/usr/bin/env bash
name='qt6-tools'
release='5'
version='6.11.1'
url='https://download.qt.io/official_releases/qt/'
description='A cross-platform application and UI framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.qt.io/official_releases/qt/${version%.*}/$version/submodules/qttools-everywhere-src-$version.tar.xz")
depends=(qt6-base)
makedepends=(vulkan-headers)
sha256sums=('8e61835a679c93fa9c6065b142353c2071ba68e297898937c32a03777fcaf50d')
group=(dev.qt)
uses=()
arch=('x86_64')

cd qttools-everywhere-src-$version
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=Release \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}


