#!/usr/bin/env bash
name='libblockdev'
release='4'
version='3.4.0'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/storaged-project/libblockdev/releases/download/$version/libblockdev-$version.tar.gz")
depends=(gawk parted kmod libyaml btrfs-progs dosfstools gptfdisk
         libbytesize ndctl xfsprogs lvm2 volume_key dmraid libnvme)
makedepends=()
sha256sums=('65ef9a37babd44b85b8ff9b273f90f9f7d5f8ff7b0c76a8edb69240325fd83f4')
group=(sys.libs)
uses=()
arch=('x86_64')

# ignore warnings. Bad idea but working
export CFLAGS="$CFLAGS -Wno-all"


cd $name-$version

prepare(){
    cd ..
    rm -rf $name-$version
    tar -xf $name-$version.tar.gz
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --without-gtk-doc
}

build(){
    make
}

package(){
    make install
}

