#!/usr/bin/env bash
name='libblockdev'
release='5'
version='3.5.0'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/storaged-project/libblockdev/releases/download/$version/libblockdev-$version.tar.gz")
depends=(gawk parted kmod libyaml btrfs-progs dosfstools gptfdisk
         libbytesize ndctl xfsprogs lvm2 volume_key dmraid libnvme)
makedepends=()
sha256sums=('bccd30e6b5d11504de60d9889ff6a2a25b07a4ec8f04070f2387e168301b3e3a')
group=(sys.libs)
uses=()
arch=('x86_64')

# ignore warnings. Bad idea but working
export CFLAGS="$CFLAGS -Wno-all"


cd $name-$version

prepare(){
    cd ..
    rm -rf $name-$version
    tar -xf $name-$version.tar.gz
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --without-gtk-doc
}

build(){
    make
}

package(){
    make install
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3
}

