#!/usr/bin/env bash
name='kapidox'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Frameworks API Documentation Tools'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kapidox-${version}.tar.xz")
depends=(py3-jinja py3-yaml)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools qt6-base)
sha256sums=( 'SKIP' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

build () {
    python -m build --wheel
}

package () {
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

