#!/usr/bin/env bash
name='coreutils'
release='6'
version='9.9'
url='https://ftp.gnu.org/gnu/coreutils/'
description='The basic file, shell and text manipulation utilities of the GNU operating system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/coreutils/coreutils-$version.tar.xz")
depends=(acl attr gmp libcap)
makedepends=(perl openssl)
sha256sums=('19bcb6ca867183c57d77155eae946c5eced88183143b45ca51ad7d26c628ca75')
uses=(openssl)
openssl_depends=(openssl)
arch=('x86_64')
group=(sys.apps)

cd $name-$version

export CFLAGS='-static-libgcc -static-libstdc++ -fPIC'

export PATH=$PATH:$HOME

prepare(){
    # fake makeinfo
    touch $HOME/makeinfo
    chmod 755 $HOME/makeinfo
}

setup(){
    autoreconf -fv
    automake -af
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --libexecdir=/usr/libexec \
        --enable-largefile \
        --enable-single-binary=symlinks \
        --enable-no-install-program=groups,hostname,kill,uptime \
        $(use_opt openssl --with-openssl --without-openssl)

}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}

