#!/usr/bin/env bash
name='milou'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='A dedicated search application built on top of Baloo'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/milou-${version}.tar.xz")
depends=(kirigami krunner ksvg libplasma qt6-base qt6-declarative)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( '8c94a4c3cef9bc625b541cb3d4c2f0a95bfa13d31f3c180633f7ef9d2701db1e' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
