#!/usr/bin/env bash
name='libXau'
release='2'
version='1.0.12'
url='https://www.x.org/wiki/'
description='X.Org X authorization library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/lib/libXau-${version}.tar.xz")
depends=(xorgproto)
makedepends=()
sha256sums=('74d0e4dfa3d39ad8939e99bda37f5967aba528211076828464d2777d477fc0fb')
uses=()
arch=('x86_64')
group=(x11.libs)

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-static \
        --enable-shared
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

