#!/usr/bin/env bash
name='cinnamon'
release='8'
version='6.6.3'
url='https://github.com/linuxmint/cinnamon'
description='Linux desktop which provides advanced innovative features and a traditional user experience'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon/archive/refs/tags/$version.tar.gz"
        "10-cinnamon-disable-polkit.patch"
        "99-cinnamon-defaults.gschema.override")
depends=(nm-applet accountsservice cinnamon-control-center cinnamon-menus
        cinnamon-session cinnamon-settings-daemon cjs gsound gstreamer libcroco
		    libgnomekbd libkeybinder3 librsvg muffin nemo polkit-gnome py3-cairo py3-dbus py3-pygobject
		    py3-pam py3-pexpect py3-pillow py3-inotify py3-tz py3-tinycss2 py3-xapp py3-requests
		    timezonemap xapp xdg-desktop-portal-xapp caribou ibus
)
makedepends=(meson gobject-introspection intltool py3-sass)
sha256sums=('12f41d7b67a81cc2f09fa728037f98cc4393da4ace94e8af0af016481cfff912'
            'SKIP'
            'SKIP')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version


prepare(){
    patch -Np1 -i ../10-cinnamon-disable-polkit.patch
}

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
    # remove broken symlink
    rm -f $DESTDIR/etc/xdg/menus/cinnamon-applications-merged
    mkdir -p $DESDTIR/usr/share/glib-2.0/schemas/
    install ../99-cinnamon-defaults.gschema.override $DESDTIR/usr/share/glib-2.0/schemas/
}
