#!/usr/bin/env bash
name='libXi'
release='2'
version='1.8.2'
url='https://gitlab.freedesktop.org/xorg/lib/libXi.git/'
description='X.Org Xi library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXi-$version.tar.gz")
depends=(libXfixes)
makedepends=()
sha256sums=('5542daec66febfeb6f51d57abfa915826efe2e3af57534f4105b82240ea3188d')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

