#!/usr/bin/env bash
name='kstatusnotifieritem'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Implementation of Status Notifier Items'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kstatusnotifieritem-${version}.tar.xz")
depends=(kwindowsystem qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( 'a2eec2a981ed9da6cffc955cc21a50dcbc77141cbb840d915f92d1897442d239' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_PYTHON_BINDINGS=OFF \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

