#!/usr/bin/env bash
name='kitemmodels'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Models for Qt Model/View system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kitemmodels-${version}.tar.xz")
depends=(qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools qt6-declarative)
sha256sums=( 'f5aec7198b161562616c139ed037e562e7ae6822b839f67c8c2e2f97678fc58e' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

