#!/usr/bin/env bash
name='kiconthemes'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Support for icon themes'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kiconthemes-${version}.tar.xz")
depends=(qt6-base qt6-svg kconfigwidgets kcolorscheme karchive kwidgetsaddons)
makedepends=(extra-cmake-modules doxygen qt6-tools breeze-icons)
sha256sums=( '6fe86f0c0ff41044f44d1f37f9ae001b8d2c1a5a8bc06c41c43ed574138af5be' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

