#!/usr/bin/env bash
name='py3-pillow'
release='7'
version='12.2.0'
url='https://python-pillow.org/'
description='Python Imaging Library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('BSD')
source=("https://github.com/python-pillow/Pillow/archive/refs/tags/${version}.tar.gz")
depends=(python freetype lcms2  libtiff  libxcb)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools libwebp)
sha256sums=('15d08a03e16953813045ad24c5818e2909ef2141a0b97b2bd3bc8ec6f222cadb')
group=(dev.python)
uses=()
arch=('x86_64')

cd "Pillow"-$version

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
}