#!/usr/bin/env bash
name='linux'
release='14'
version='7.0.5'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=( )
makedepends=(mklinux)
sha256sums=()
uses=()
arch=('x86_64')
group=(sys.kernel)
# Kernel module strip make garbage it.
dontstrip="31"

prepare(){
    wget https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-$version.tar.xz -O - | tar -xJvf -
}

package(){
    # install kernel (archlinux kernel config used)
    ALLOWROOT=1 bash mklinux -f -q -x -o "$DESTDIR" -t local -b linux-$version \
     -c "https://gitlab.archlinux.org/archlinux/packaging/packages/linux-hardened/-/raw/main/config.x86_64"  \
     -v $version -y 1
    # remove headers (for fix conflict with linux-headers)
    rm -rf ${DESTDIR}/usr/include
    # remove broken symlink if exists
    rm -rf ${DESTDIR}/lib/modules/$version/build/linux-$version || true
    # decompress kernel modules (if gzipped)
    find ${DESTDIR}/lib/modules -iname "*.ko.gz" -exec gzip -d {} \;
    # decompress kernel modules (if xzed)
    find ${DESTDIR}/lib/modules -iname "*.ko.xz" -exec xz -d {} \;
}

