#!/usr/bin/env bash
name='mklinux'
release='5'
version='20260223'
url='https://gitlab.com/turkman/devel/sources/mklinux'
description='kernel builder'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mklinux/-/archive/$version/mklinux-$version.zip")
depends=(bc findutils file tar elfutils gcc binutils bison flex make kmod rsync)
makedepends=()
sha256sums=('42f992e40459fd1e1a47cec3b59d5a0fe4ee081ae205db3acd2c9ec83289e8dc')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version

package(){
    bash mklinux.sh -g -o $DESTDIR
    install mkfw.sh $DESTDIR/usr/bin/mkfw
}

