#!/usr/bin/env bash
name='kcalendarcore'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='The KDE calendar access library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcalendarcore-${version}.tar.xz")
depends=(libical qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( '4228869722c5bb5325b7c5b10555e6b747bde0e36cbd43519d8681fe3b383173' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

