#!/usr/bin/env bash
name='py3-lxml'
release='3'
version='6.1.0'
url='https://pypi.org/project/lxml/'
description='Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxml/lxml/archive/refs/tags/lxml-$version.tar.gz")
depends=(python libxml2 libxslt py3-cython)
makedepends=()
sha256sums=('d62d3f15631982e884920d20a89d89ff059b33b373314f9e1973f4e18129898a')
group=(dev.python)
uses=()
arch=('x86_64')


cd lxml-lxml-$version

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

