#!/usr/bin/env bash
name='libsass'
release='2'
version='3.6.6'
url='https://sass-lang.com/libsass'
description='C/C++ implementation of a Sass compiler'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/sass/libsass/archive/${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('11f0bb3709a4f20285507419d7618f3877a425c0131ea8df40fe6196129df15d')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

