#!/usr/bin/env bash
name='kauth'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Abstraction to system policy and authentication features'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kauth-${version}.tar.xz")
depends=(qt6-base kcoreaddons kwindowsystem polkit-qt6)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( '741934765f0c9f1c535598203fbad3f1b97231cc683a218a7f39fab948c13eab' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


