#!/usr/bin/env bash
name='lightdm-pardus-greeter'
release='8'
version='0.4.13'
url='https://github.com/pardus/pardus-lightdm-greeter'
description='Lightdm greeter for Pardus'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pardus/pardus-lightdm-greeter/archive/refs/tags/debian/$version.tar.gz")
depends=(lightdm py3-pygobject py3-cairo )
makedepends=()
sha256sums=('df9d9bc8cfc185d15530378d42556656538bdd137f907ef0519ac72c3b9d6d2f')
group=(x11.misc)
uses=()
arch=('x86_64')

cd pardus-lightdm-greeter-debian-$version

setup(){
    meson setup build \
        --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

