#!/usr/bin/env bash
name='py3-setproctitle'
release='3'
version='1.3.7'
url='https://github.com/dvarrazzo/py-setproctitle'
description='A Python module to customize the process title'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD-3-Clause')
source=("https://github.com/dvarrazzo/py-setproctitle/archive/refs/tags/version-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('e34ad337c3be087da1052e8846c6576a5816e0fcbf0a8ba9dd170e205166e533')
group=(dev.python)
uses=()
arch=('x86_64')

cd "py-setproctitle-version"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}


