#!/usr/bin/env bash
name='py3-cython'
release='4'
version='3.2.4'
url='https://cython.org/'
description='A Python to C compiler.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/cython/cython/archive/refs/tags/$version.tar.gz")
depends=(python libxml2 libxslt)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('9631e586c49b9d3f72c3962c376119479a6a98e3c0e3c14d5218e199ef563b18')
group=(dev.python)
uses=()
arch=('x86_64')

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS


cd cython-$version

build(){
    python3 setup.py build
}

package(){
  python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

