#!/usr/bin/env bash
name='pipewire'
release='3'
version='1.6.3'
url='https://pipewire.org/'
description='Multimedia processing graphs'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/$version/pipewire-$version.tar.gz"
        "https://github.com/my-garbage-stuff/pipewire-system/archive/refs/tags/1.0.0.tar.gz")
depends=(lilv libpulse alsa-lib dbus)
makedepends=()
sha256sums=('93db72dc06768db548d48ae2b8e96e7c299c89a47f5c4426f152221aa90b0f2d'
            '8d6f920086b628004c2114c0166280bef898633a149005e39fa9f281a18052a1')
group=(media.video)
uses=(alsa gstreamer bluetooth jack)
uses_extra=(v4l2)
bluetooth_depends=(bluez)
arch=('x86_64')

cd $name-$version

unset CFLAGS
unset CXXFLAGS

setup(){

   meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
    -D gstreamer=$(use_opt gstreamer enabled disabled)\
    -D gstreamer-device-provider=$(use_opt gstreamer enabled disabled) \
    -D pipewire-alsa=$(use_opt alsa enabled disabled)\
    -D alsa=$(use_opt alsa enabled disabled)\
    -D jack=$(use_opt jack enabled disabled)\
    -D bluez5=$(use_opt bluetooth enabled disabled)\
    -D bluez5-backend-hsp-native=$(use_opt bluetooth enabled disabled)\
    -D bluez5-backend-hfp-native=$(use_opt bluetooth enabled disabled)\
    -D bluez5-codec-opus=$(use_opt bluetooth enabled disabled)\
    -D v4l2=$(use_opt v4l2 enabled disabled)\
    -D session-managers=[]
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/usr/libexec ${DESTDIR}/etc/xdg/autostart/ ${DESTDIR}/etc/profile.d
    make install -C  ../pipewire-system-1.0.0
}

