#!/usr/bin/env bash
name='dkms'
release='3'
version='3.4.3'
url='https://github.com/dell/dkms'
description='Dynamic Kernel Module Support'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/dell/dkms/archive/refs/tags/v$version.tar.gz")
depends=(bash coreutils gcc mklinux sed patch linux-headers)
makedepends=()
sha256sums=('a8032b3e4eb7cd86ae9b6ffd16fc4fda84c95fa47a0f5aa2010d872d0a5b0b5e')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version


package () {
    make KCONF=/../trash \
        install $jobs
}

