#!/usr/bin/env bash
name='cinnamon-desktop'
release='7'
version='6.6.2'
url='https://github.com/linuxmint/cinnamon-desktop'
description='Library with common API for various Cinnamon modules'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-desktop/archive/$version/cinnamon-desktop-$version.tar.gz")
depends=(libpulse)
makedepends=(libXinerama libxkbfile)
sha256sums=('4ed0d52a072551c6d536f1be68d4fcdb4166454fc9e48567ab2550282086b0f4')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

