#!/usr/bin/env bash
name='cinnamon-desktop'
release='6'
version='6.6.1'
url='https://github.com/linuxmint/cinnamon-desktop'
description='Library with common API for various Cinnamon modules'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-desktop/archive/$version/cinnamon-desktop-$version.tar.gz")
depends=(libpulse)
makedepends=(libXinerama libxkbfile)
sha256sums=('4b240bda723f965ef9e024d9509aca42459f31bf6ea6d9ce770659bb26880e91')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

