#!/usr/bin/env bash
name='kpackage'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Framework that lets applications manage user installable packages of non-binary assets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpackage-${version}.tar.xz")
depends=(qt6-base karchive ki18n kcoreaddons)
makedepends=(doxygen extra-cmake-modules qt6-tools kdoctools)
sha256sums=( '5fa4b07f729c3ff6b7f362d318374810fa55b13a922d2b240462eb8efc1045e8' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

