#!/usr/bin/env bash
name='aurorae'
release='2'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Themeable window decoration for KWin'
email='aliriza.keskin@pardus.org.tr'
maintainer='sulincix'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/aurorae-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules)
sha256sums=( '538223ebe7521305d29873c278f85e7910eb7810a31d2a69698ede76a5c0da3c' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
