#!/usr/bin/env bash
name='flatpak-builder'
release='3'
version='1.4.10'
url='https://salsa.debian.org/debian/flatpak-builder'
description='Sandboxed app framework - developer tools'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/flatpak/flatpak-builder/releases/download/$version/flatpak-builder-$version.tar.xz")
depends=(flatpak elfutils git patch dconf debugedit)
makedepends=()
sha256sums=('b1721078c0697c8ca1d7db965232b509d1aa87f68b4dae378eb500bddddb9cc1')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/ \
       -Dfuse=3

}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

