#!/usr/bin/env bash
name='hyprwayland-scanner'
release='3'
version='0.4.5'
url='https://github.com/hyprwm/hyprwayland-scanner'
description='A Hyprland implementation of wayland-scanner, in and for C++.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprwayland-scanner/archive/refs/tags/v$version.tar.gz")
depends=(hyprutils glib pugixml)
makedepends=()
sha256sums=('2125d279eea106e3e6c8dc9fa15181c75d67467b5352d24e2a07903b10abad62')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

