#!/usr/bin/env bash
name='shadow'
release='4'
version='4.19.4'
url='https://github.com/shadow-maint/shadow/releases'
description='Password and account management tool suite with support for shadow files and PAM'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/shadow-maint/shadow/releases/download/$version/shadow-$version.tar.xz"
        "useradd.defaults"
        "shadow.sysconf"
        "system-auth")
depends=(pam libxcrypt acl attr)
makedepends=( )
sha256sums=('ce57a313e315a0a7cb04a8f50cc20753e994e487bbe9b78a2a824ca75cb486c0'
         'SKIP'
         'SKIP'
         'SKIP')
uses=()
arch=('x86_64')
group=(sys.apps)

cd $name-$version

setup(){
    autoreconf -fiv
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --sysconfdir=/etc \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --disable-account-tools-setuid \
        --without-sssd \
        --with-fcaps \
        --with-libpam \
        --without-group-name-max-length \
        --without-selinux \
        --without-libbsd \
        --without-su \
        --with-yescrypt \
        --without-bcrypt \
        --disable-nls \
        --disable-logind
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # remove selinux stuff
    sed -i "/.*selinux.*/d" ${DESTDIR}/etc/pam.d/*
    install -vDm 600 ../useradd.defaults "${DESTDIR}/etc/default/useradd"
    install -vDm 600 ../system-auth "${DESTDIR}/etc/pam.d/system-auth.d/50-shadow"
    install -vDm 755 ../shadow.sysconf ${DESTDIR}/etc/sysconf.d/shadow
}

