#!/usr/bin/env bash
name='hyprgraphics'
release='2'
version='0.4.0'
url='https://github.com/hyprwm/hyprgraphics'
description='Hyprland graphics / resource utilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprgraphics/archive/refs/tags/v$version.zip")
depends=(cairo file libjpeg-turbo libjxl libwebp)
makedepends=()
sha256sums=('c82cab599dd235e0039d0fac7168d86682ea22863239cc57bb2c4a3294c12394')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

