#!/usr/bin/env bash
name='bluedevil'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Integrate the Bluetooth technology within KDE workspace and applications'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/bluedevil-${version}.tar.xz")
depends=(bluez-qt kdeclarative kcmutils kconfig
         kcoreaddons kdbusaddons ki18n kio kjobwidgets knotifications
         kwidgetsaddons kwindowsystem qt6-declarative)
makedepends=(ksvg extra-cmake-modules kdoctools kcmutils)
sha256sums=( '3fdab4a724ba246a10f2637076ca5332788fff5c3c6193ccf34eb031e8973e9d' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


