#!/usr/bin/env bash
name='pkgconf'
release='5'
version='2.9.93'
url='https://github.com/pkgconf/pkgconf/tags'
description='Package compiler and linker metadata toolkit'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pkgconf/pkgconf/archive/refs/tags/pkgconf-$version.tar.gz"
        "x86_64-pc-linux-gnu.personality"
        "i686-pc-linux-gnu.personality"
)
depends=( )
makedepends=( )
sha256sums=('b9632d0d91321f56645de720fd8cd3584b0d0ca8ff13a3d9d5285888869fcc98'
         'SKIP'
         'SKIP')
uses=()
arch=('x86_64')
group=(dev.util)
cd $name-$name-$version

setup(){
    sh ./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --with-pkg-config-dir=/usr/share/pkgconfig:/usr/lib64/pkgconfig:/lib64/pkgconfig
}

build(){
    make $jobs
}

package(){
    make install $jobs
    ln -s pkgconf ${DESTDIR}/usr/bin/pkg-config
    install -Dt "${DESTDIR}/usr/share/pkgconfig/personality.d" -m644 \
    ../i686-pc-linux-gnu.personality \
    ../x86_64-pc-linux-gnu.personality
}

