#!/usr/bin/env bash
name='polkit-kde-agent'
release='5'
version='6.7.0'
url='https://kde.org/plasma-desktop/'
description='Daemon providing a polkit authentication UI for KDE'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/polkit-kde-agent-1-$version.tar.xz")
depends=(polkit kiconthemes kdbusaddons kcrash)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( '0f27ff2aa3610418620c42804b9c3dc22f6979e5c03822f93979d44fbed1dabf' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-1-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}
build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

