#!/usr/bin/env bash
name='bluez-qt'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for Bluez 5 DBus API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/bluez-qt-${version}.tar.xz")
depends=(qt6-base bluez)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=( '3e22c1f71f3d93f572c2a1126edc2aa16151f8bad10f9f1ddb7e41dd372aee70' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
