#!/usr/bin/env bash
name='py3-cffi'
release='5'
version='2.0.0'
url='https://pypi.org/project/cffi/'
description='Foreign Function Interface for Python calling C code.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/python-cffi/cffi/archive/refs/tags/v${version}.tar.gz")
#source=("https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz")
depends=(python py3-cparser libffi)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('e32bea840b50779a43dcaff13dcf6fa8bc29aa1b071c2cb4e27c1bd79114a202')
group=(dev.python)
uses=()
arch=('x86_64')

cd cffi-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

