#!/usr/bin/env bash
name='plasma-workspace'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Kde Plasma Workspace'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-workspace-$version.tar.xz")
depends=(accountsservice kactivitymanagerd kded  kio
         kquickcharts kwin milou pipewire phonon prison kunitconversion
         plasma-integration qt6-base xdotool qcoro-qt6 ktexteditor
         plasma5support plasma-activities-stats knotifyconfig)
makedepends=(qt6-tools)
sha256sums=( '9a7f2a04e8a44bf24da4d294bba270984a090ef17a082cd1eb25cb8182651d3c' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

export LANG="C.UTF-8"
export LC_ALL=$LANG

prepare(){
set -x
    sed -i "s/ Location / /g" CMakeLists.txt
    sed -i "s/ Wallet / /g" CMakeLists.txt
    sed -i "/find_package(KSysGuard.*/d" CMakeLists.txt
    sed -i "/.*libqalculate.*/d" CMakeLists.txt
    sed -i "/.*systemmonitor.*/d" CMakeLists.txt
    sed -i "/.*soliduiserver.*/d" CMakeLists.txt
    ## subdir: kcms
    sed -i "/.*users.*/d" kcms/CMakeLists.txt
    ## subdir : applets
    sed -i "/.*systemmonitor.*/d" applets/CMakeLists.txt
    sed -i "/.*devicenotifier.*/d" applets/CMakeLists.txt
    ## subdir : runners
    sed -i "/.*kill.*/d" runners/CMakeLists.txt
}

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DGLIBC_LOCALE_GEN=OFF \
        -DBUILD_TESTING=OFF
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
    # fix symlinks
    rm -f $DESTDIR//usr/bin/lookandfeeltool
    ln -s plasma-apply-lookandfeel $DESTDIR//usr/bin/lookandfeeltool
}

