#!/usr/bin/env bash
name='speech-dispatcher'
release='2'
version='0.12.1'
url='https://github.com/brailcom/speechd'
description='Speech synthesis interface'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/brailcom/speechd/archive/refs/tags/$version.tar.gz")
depends=(dotconf libaio libpulse)
makedepends=()
sha256sums=('32a730f6fb5981b9bec7e04f3674fd7d29e54935f46cf6354dbb9ab1f9b23b2d')
group=(app.accessibility)
uses=()
arch=('x86_64')

cd speechd-$version

prepare(){
    # fake makeinfo command
    > $HOME/makeinfo
    chmod +x $HOME/makeinfo
}

setup () {
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc \
        --with-ibmtts=no \
        --with-kali=no \
        --with-baratinoo=no \
        --with-voxin=no \
        --without-flite
}

build () {
    make $jobs
}

package () {
    make install $jobs
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3
}

