#!/usr/bin/env bash
name='libXcomposite'
release='2'
version='0.4.7'
url='https://gitlab.freedesktop.org/xorg/lib/libXcomposite'
description='X.Org Xcomposite library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/lib/libxcomposite/-/archive/libXcomposite-$version/libxcomposite-libXcomposite-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('61b3608697abb4f3fa80782423b924d26aea77f8e66084658b26196572195dab')
group=(x11.libs)
uses=()
arch=('x86_64')

cd libxcomposite-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

