#!/usr/bin/env bash
name='kirigami'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick based components set'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kirigami-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-shadertools)
sha256sums=( 'd7daa74e9fe81b674e54e6e979feb85d3d2f4216bf6d9c02bfaa2c021fe1ac2d' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

