#!/usr/bin/env bash
name='kdav'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='A DAV protocol implemention with KJobs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdav-${version}.tar.xz")
depends=(ki18n kcoreaddons kio qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( 'e0af4190960d65f5c8475f01213ea4e68a07763ffeaa6766de4b7f50529e0498' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DDocBookXSL_DIR=/usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
