#!/usr/bin/env bash
name='grep'
release='3'
version='3.12'
url='https://ftp.gnu.org/gnu/grep/'
description='GNU regular expression matcher'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/grep/grep-$version.tar.xz")
depends=(libpcre2)
makedepends=()
sha256sums=('2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

prepare(){
    # emptly makeinfo
    echo "#!/bin/sh" > ~/makeinfo
    chmod 755 ~/makeinfo
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

