#!/usr/bin/env bash
name='libxkbcommon'
release='4'
version='1.13.1'
url='https://github.com/xkbcommon/libxkbcommon'
description='keymap handling library for toolkits and window systems'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-$version.tar.gz")
depends=(libxml2 libxcb xkeyboard-config)
makedepends=()
sha256sums=('aeb951964c2f7ecc08174cb5517962d157595e9e3f38fc4a130b91dc2f9fec18')
group=(x11.libs)
uses=(wayland)
wayland_depends=(wayland-protocols wayland)
arch=('x86_64')

cd libxkbcommon-xkbcommon-$version

setup(){
    meson setup build \
        --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Denable-docs=false \
        -Denable-wayland=$(use_opt wayland true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

