#!/usr/bin/env bash
name='py3-xapp'
release='3'
version='3.0.2'
url='https://github.com/linuxmint/python3-xapp'
description='Python Xapp Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://github.com/linuxmint/python3-xapp/archive/refs/tags/${version}.tar.gz")
depends=(python py3-psutil)
makedepends=(meson)
sha256sums=('2078766e2553eea0ff2ee598212d4883a226df63d014d060756c6274db024823')
group=(dev.python)
uses=()
arch=('x86_64')

#cd "python3-xapp"-$version

setup(){
    meson build "python3-xapp"-$version \
        --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    meson compile -C build
}

package(){
    meson install -C build
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

