#!/usr/bin/env bash
name='kate'
release='6'
version='26.04.2'
url='https://kde.org/applications/utilities/org.kde.kate'
description='A multi-document, multi-view text editor'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL' 'LGPL' 'FDL')
source=("https://invent.kde.org/utilities/kate/-/archive/v${version}/kate-v${version}.tar.gz")
depends=(knewstuff ktexteditor hicolor-icon-theme)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'f34f126c76f48f8698adb6197580d6feaf077fc760df1621aca9a4752f2a1eb6' )
group=(kde.apps)
uses_extra=(kwrite)
uses=()
arch=('x86_64')

cd $name-"v"$version

setup(){
  cmake -B build/kate -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_kwrite=FALSE

  if use kwrite ; then
	  cmake -B build/kwrite -G Ninja \
  		-DCMAKE_INSTALL_PREFIX=/usr \
		  -DCMAKE_INSTALL_LIBDIR=lib64 \
		  -DBUILD_kate=FALSE \
		  -DBUILD_addons=FALSE
  fi
}

build () {
	cmake --build build/kate
  if use kwrite ; then
	    cmake --build build/kwrite
  fi

}

package () {
    DESTDIR="$DESTDIR" cmake --install build/kate
  if use kwrite ; then
   	DESTDIR="$DESTDIR" cmake --install build/kwrite
  fi
}

