#!/usr/bin/env bash
name='qt6-remoteobjects'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Inter-process communication (IPC) module developed for Qt'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtremoteobjects-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('40629895c69531a687a9c0258316cee3f04c2d18b2bf2ad36dc83e76a58f111a')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtremoteobjects-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
