#!/usr/bin/env bash
name='layer-shell-qt'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Qt component to allow applications to make use of the Wayland wl-layer-shell protocol'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/layer-shell-qt-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland)
makedepends=(extra-cmake-modules wayland-protocols)
sha256sums=( 'e6f48b6ebe2c3caaa3c2ef6d8470550904d030ad3496bc10a5409875db2daab0' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_TESTING=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
