#!/usr/bin/env bash
name='tdb'
release='2'
version='1.4.15'
url='https://tdb.samba.org/'
description='Simple database API '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.samba.org/ftp/tdb/tdb-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('fba09d8df1f1b9072aeae8e78b2bd43c5afef20b2f6deefa633aa14a377a8dd2')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
  ./configure --prefix=/usr \
      --libdir=/usr/lib64/

}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

