#!/usr/bin/env bash
name='sonnet'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Spelling framework for Qt5'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/sonnet-${version}.tar.xz")
depends=(qt6-base hunspell)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools doxygen)
sha256sums=( 'f8dcbba58d3479dfa4922146270f6ecb7ce0d987d82edc59b0c7c27ff965f65a' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

