#!/usr/bin/env bash
name='hyprutils'
release='3'
version='0.11.0'
url='https://github.com/hyprwm/hyprutils'
description='Hyprland utilities library used across the ecosystem'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprutils/archive/refs/tags/v$version.zip")
depends=(pixman)
makedepends=()
sha256sums=('8ded755197f252c90fdae39791f20ebb0f51d202a5d3d81a3e4bc34348092c58')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

