#!/usr/bin/env bash
name='util-macros'
release='3'
version='1.20.2'
url='https://gitlab.freedesktop.org/xorg/util/macros'
description='X.Org autotools utility macros'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/util/util-macros-${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('f642f8964d81acdf06653fdf9dbc210c43ce4bd308bd644a8d573148d0ced76b')
arch=('x86_64')
group=(x11.misc)

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

