#!/usr/bin/env bash
name='kio'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Resource and network access abstraction'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kio-${version}.tar.xz")
depends=(karchive kbookmarks kcompletion kconfig kconfigwidgets kcoreaddons kcrash kauth
	kdbusaddons ki18n kiconthemes kitemviews kjobwidgets kservice kwidgetsaddons kwindowsystem solid qt6-base qt6-5compat solid)
makedepends=(doxygen extra-cmake-modules libxml2 libxslt qt6-tools)
sha256sums=( 'fc201b02c277a35ce81414b1de7e6f851e46b0b5d43beb784936a4a6dc6167d0' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version


setup () {
  cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

