#!/usr/bin/env bash
name='libxcvt'
release='2'
version='0.1.3'
url='https://gitlab.freedesktop.org/xorg/lib/libxcvt'
description='X.Org xcvt library and cvt program'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/lib/libxcvt/-/archive/libxcvt-$version/libxcvt-libxcvt-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('5edaa65f5abd94ae12030b52fda66828eb8a41396aa9c02fd2c6210445fff61e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

