#!/usr/bin/env bash
name='kcolorscheme'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Classes to read and interact with KColorScheme'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcolorscheme-${version}.tar.xz")
depends=(qt6-base kconfig kguiaddons ki18n)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=( '574e12350ea1adf248c5263cf18d145476d368664a302514d1065aa2563e1efd' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
