#!/usr/bin/env bash
name='openssh'
release='7'
version='10.3p1'
url='https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable'
description='OpenBSD ssh server & client'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$version.tar.gz"
        "sshd.initd"
        "sshd.confd")
depends=(zlib libxcrypt openssl libmd)
makedepends=()
sha256sums=('56682a36bb92dcf4b4f016fd8ec8e74059b79a8de25c15d670d731e7d18e45f4'
         'SKIP'
         'SKIP')
group=(net.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc/ssh \
        --without-pam \
        --disable-strip \
        --with-ssl-engine \
        --with-privsep-user=nobody \
        --with-pid-dir=/run \
        --with-default-path='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
}

build(){
    make $jobs
}

package(){
    make install $jobs DESTDIR="${DESTDIR}"
    install -m755 -D ../sshd.initd "$DESTDIR"/etc/init.d/sshd
    install -m755 -D ../sshd.confd "$DESTDIR"/etc/conf.d/sshd
}

