#!/usr/bin/env bash
name='ca-certificates'
release='3'
version='20251003'
url='https://gitlab.alpinelinux.org/alpine/ca-certificates'
description='Common CA certificates'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.alpinelinux.org/alpine/ca-certificates/-/archive/$version/ca-certificates-$version.tar.gz"
        "ca-certificates.sysconf")
depends=()
makedepends=()
sha256sums=('7e8b82de0e308d3bf4fc39ac115bf407a252bb2acb2cfc6b6db4b3d4c788146e'
         'SKIP')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make $jobs
}

package(){
    make install $jobs
    # openssl conflict fix
    rm -f ${DESTDIR}/usr/bin/c_rehash
    # install sysconf file
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../ca-certificates.sysconf ${DESTDIR}/etc/sysconf.d/ca-certificates
}

