#!/usr/bin/env bash
name='kdecoration'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Plugin based library to create window decorations'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kdecoration-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=( 'acfe5657d889bf0dd5b8b50132bbe9c62f48b5074fcba8265a1cb84d6c227b5d' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
