#!/usr/bin/env bash
name='kscreen'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='KDE screen management software'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kscreen-${version}.tar.xz")
depends=(kcmutils kconfig kcoreaddons kdbusaddons kdeclarative ki18n kirigami ksvg kwindowsystem libplasma libkscreen libX11 libxcb libXi qt6-base qt6-declarative qt6-sensors layer-shell-qt)
makedepends=(extra-cmake-modules )
sha256sums=( 'ad57a4326a64979a68aa5068a7151702d9b02db0720670e4be3e178905beda56' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
