#!/usr/bin/env bash
name='aquamarine'
release='3'
version='0.10.0'
url='https://github.com/hyprwm/aquamarine'
description='Aquamarine is a very light linux rendering backend library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/aquamarine/archive/refs/tags/v$version.tar.gz")
depends=(hyprwayland-scanner libglvnd libglvnd libinput mesa seatd wayland libdisplay-info hwdata)
makedepends=()
sha256sums=('0ec80c86dd94d7f2836aac9ed415b9170109bd77048de791d837ee729f1ad76a')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

