#!/usr/bin/env bash
name='qt6-serialbus'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Qt module for general purpose serial bus access'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtserialbus-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-serialport)
makedepends=(cmake ninja)
sha256sums=('c46c9c0c8d6815301a669cdbd5866c10bcfb9e56889f5d7da14e11d6ad24f20a')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtserialbus-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
