#!/usr/bin/env bash
name='btrfs-progs'
release='9'
version='6.17.1'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/kdave/btrfs-progs/archive/refs/tags/v${version}.tar.gz")
depends=(e2fsprogs zlib libgcrypt eudev)
makedepends=()
sha256sums=('6eba55443b7c0c4dfa91619f8629cfa75e27734f76e564ca83bff6b6e344a5ff')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	./autogen.sh
	./configure --prefix=/usr \
            --libdir=/usr/lib64/\
            --with-crypto=libgcrypt \
            --disable-zstd \
            --disable-documentation
}

build(){
    make $jobs
}

package(){
  make DESTDIR="$DESTDIR" install install_python
  # install bash completion (FS#44618)
  install -Dm644 btrfs-completion "$DESTDIR/usr/share/bash-completion/completions/btrfs"
}

