#!/usr/bin/env bash
name='kcoreaddons'
release='8'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtCore'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcoreaddons-${version}.tar.xz")
depends=(qt6-base breeze-icons)
makedepends=(clang extra-cmake-modules graphviz qt6-tools doxygen)
sha256sums=( 'ad0d0147968dabdcf011425cf7764e71a0d0cfdc30e9e34b561ea5ba9a768001' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
   -DBUILD_PYTHON_BINDINGS=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
    	-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


