#!/usr/bin/env bash
name='libX11'
release='2'
version='1.8.13'
url='https://www.x.org/archive/individual/lib/'
description='X.Org X11 library'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libX11-$version.tar.xz")
depends=(libxcb libXau libXdmcp xtrans)
makedepends=()
sha256sums=('69606f485c2c07c14ef64f75b7bb326d48587af33795d9ab3e607c0b5f94f11c')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
