#!/usr/bin/env bash
name='kdeplasma-addons'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description=''
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/kdeplasma-addons-$version.tar.xz")
depends=(plasma-workspace)
makedepends=()
sha256sums=( '8b86b0b79b0af2da097d81dce099913d43574e08c4428a7925870692178b4298' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # remove corrosion dependency (and rust bullshits)
    sed -i "/.*Corrosion.*/d" CMakeLists.txt
    sed -i "/.*kameleon.*/d" kdeds/CMakeLists.txt
}

setup () {
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

