#!/usr/bin/env bash
name='plasma-activities-stats'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Qt Platform Theme integration plugins for the Plasma workspaces'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-stats-${version}.tar.xz")
depends=(plasma-activities kconfig qt6-base)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=( '2b4aaed9c4685bc2c056a0cba84d427ef2f1eb7a4f841d5877d0347b5b11cc13' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}