#!/usr/bin/env bash
name='py3-wheel'
release='6'
version='0.47.0'
url='https://pypi.org/project/wheel/'
description='A built-package format for Python'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pypa/wheel/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-installer py3-flit)
sha256sums=('7077424e2d404e5ed1c1be5075b05afa1807ccf251939a5e753567fdcfcd7a58')
group=(dev.python)
uses=()
arch=('x86_64')

cd wheel-$version

prepare(){
: #  rm -r src/wheel/vendored
}

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

