#!/usr/bin/env bash
name='flatpak-kcm'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Flatpak Permissions Management KCM'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/flatpak-kcm-${version}.tar.xz")
depends=(flatpak kitemmodels kcmutils)
makedepends=(extra-cmake-modules)
sha256sums=( '4a6490696eb4c86438b04e97dc163be50b0cd7bb7eacfbb204692094ff60b76b' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
