#!/usr/bin/env bash
name='kunitconversion'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Support for unit conversion'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kunitconversion-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools)
sha256sums=( '404e064114c95eca0ef759b96ca4e0ba5f9b8bc563138574358270963f3f5554' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_PYTHON_BINDINGS=OFF \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

