#!/usr/bin/env bash
name='plasma-nm'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop/'
description='Plasma applet written in QML for managing network connections'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-nm-$version.tar.xz")
depends=(kcmutils kcolorscheme kcompletion kconfig kcoreaddons kdbusaddons kdeclarative ki18n kio kirigami knotifications kquickcharts
         ksvg kwidgetsaddons kwindowsystem libplasma modemmanager-qt networkmanager-qt prison qca qcoro-qt6 qt6-base qt6-declarative solid
        qt6-qtkeychain)
makedepends=(extra-cmake-modules)
sha256sums=( 'b29680cc17c4bbe52e3b988d5be437ec4b524b554fa180ead13bc8910144cf98' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja\
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build $jobs install
}

