#!/usr/bin/env bash
name='ibus'
release='2'
version='1.5.34'
url='https://github.com/ibus/ibus/wiki'
description='Intelligent Input Bus'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/ibus/ibus/archive/refs/tags/$version.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('ff8f511770844203108119727dc8686c29afb286e9cb535e0870f18d40fddbbb')
group=(app.i18n)
uses=()
arch=('x86_64')

cd $name-$version

export CFLAGS="-Wno-all"

setup () {
    autoreconf -fvi
    ./configure --prefix=/usr \
     --libdir=/usr/lib64/ \
     --disable-gtk-doc \
  		--disable-memconf \
 		--disable-python2 \
 		--disable-gtk4 \
 		--disable-gtk2 \
		--disable-emoji-dict \
    --disable-unicode-dict \
 		--disable-systemd-services

rm -f tools/main.c

}

build () {
    make $jobs
}

package () {
    make install $jobs
}

