#!/usr/bin/env bash
name='kirigami-addons'
release='5'
version='1.12.1'
url='https://invent.kde.org/libraries/kirigami-addons'
description='Add-ons for the Kirigami framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz")
depends=(kirigami qt6-multimedia)
makedepends=(extra-cmake-modules ki18n)
sha256sums=( 'c543a493ce5875f405fb1c9ff6d531060ed082cc6d710e56d46ac42d164207bb' )
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

