#!/usr/bin/env bash
name='modemmanager-qt'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for modemmanager API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/modemmanager-qt-${version}.tar.xz")
depends=(modemmanager qt6-base )
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( 'a893a169dd40c430c51d39326b1af0aab2a9d6c20adc34f2b8e6332c152f6234' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

