#!/usr/bin/env bash
name='kglobalacceld'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Daemon providing Global Keyboard Shortcut (Accelerator) functionality'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kglobalacceld-${version}.tar.xz")
depends=(kconfig kcoreaddons kcrash kdbusaddons kglobalaccel kio kjobwidgets kservice kwindowsystem libX11
         libxcb qt6-base xcb-util-keysyms)
makedepends=(extra-cmake-modules)
sha256sums=( 'ff5e36dcbcb8182f1b695062993a9ea2cc73d267536b2f5926de039fa7732c65' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
