#!/usr/bin/env bash
name='kcompletion'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Text completion helpers and widgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcompletion-${version}.tar.xz")
depends=(kconfig kcodecs kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( '006864dcba5d5fc87b4ca5dcc1239538657a5d052057bae5d3bc3e71eaba0551' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


