#!/usr/bin/env bash
name='konsole'
release='6'
version='26.04.2'
url='https://kde.org/applications/system/konsole'
description="KDE's terminal emulator"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'GPL' 'FDL')
source=("https://download.kde.org/stable/release-service/${version}/src/konsole-${version}.tar.xz")
depends=(kpty kparts knewstuff knotifyconfig)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'd81a696d6a316d0c8fabe3cecd83783f656ee97c70ced89513b3fd16e9d216ac' )
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_PLUGIN_SSHMANAGER=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

