#!/usr/bin/env bash
name='kactivitymanagerd'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description="System service to manage user's activities and track the usage patterns"
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kactivitymanagerd-${version}.tar.xz")
depends=(kconfig kcoreaddons kcrash kglobalaccel ki18n kio kservice kwindowsystem kxmlgui qt6-base)
makedepends=(extra-cmake-modules boost)
sha256sums=( 'ed065c2d76c85cf8e10dd72ff8f89e72136fc4c85561a6c985eb97dc518446a1' )
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
