#!/usr/bin/env bash
name='ksvg'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Components for handling SVGs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ksvg-${version}.tar.xz")
depends=(kconfig kcoreaddons kguiaddons qt6-base qt6-svg)
makedepends=(extra-cmake-modules kirigami qt6-declarative qt6-tools)
sha256sums=( '68d43f014639ae6097012cdd67bdbbefd5425b17d2322d94f55be2b138613e0a' )
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
