#!/usr/bin/env bash
name='ark'
release='6'
version='26.04.2'
url='https://kde.org/applications/utilities/org.kde.ark'
description='Graphical file compression/decompression utility with support for multiple formats'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/ark-${version}.tar.xz")
depends=(kio libarchive kparts kfilemetadata kpty)
makedepends=()
sha256sums=( 'b81c4055486c99f4f21ff228bf12485bc73e8e6b0064edee1043a11ad5d1e555' )
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
