#!/usr/bin/env bash
name='threadweaver'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='High-level multithreading framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/threadweaver-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=( '6be89d43b4d7cfd4ce519ed24b8bcf8400c93bcfc6f42d9931cd0f852269bdcb' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
