#!/usr/bin/env bash
name='tzdata'
release='3'
version='2026a'
url='https://www.iana.org/time-zones'
description='Timezone data'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('Public-Domain')
source=("https://www.iana.org/time-zones/repository/releases/tzcode$version.tar.gz"
	      "https://www.iana.org/time-zones/repository/releases/tzdata$version.tar.gz"
	      "tzdata.sysconf")
depends=()
makedepends=()
sha256sums=('f80a17a2eddd2b54041f9c98d75b0aa8038b016d7c5de72892a146d9938740e1'
            '77b541725937bb53bd92bd484c0b43bec8545e2d3431ee01f04ef8f2203ba2b7'
            'SKIP')
group=(dev.libs)
uses=()
arch=('x86_64')

build () {
    make $jobs
}


# Thx alpine linux
_timezones="africa antarctica asia australasia europe northamerica \
	southamerica etcetera backward factory"
package() {
	./zic -b fat -y ./yearistype -d "$DESTDIR"/usr/share/zoneinfo $_timezones
	./zic -b fat -y ./yearistype -d "$DESTDIR"/usr/share/zoneinfo/right -L leapseconds $_timezones
	./zic -b fat -y ./yearistype -d "$DESTDIR"/usr/share/zoneinfo/posix $_timezones

	./zic -b fat -y ./yearistype -d "$DESTDIR"/usr/share/zoneinfo -p America/New_York
	install -m444 -t "$DESTDIR"/usr/share/zoneinfo iso3166.tab zone1970.tab zone.tab

	install -Dm755 -t "$DESTDIR"/usr/sbin zic zdump

	install -Dm644 -t "$DESTDIR"/usr/share/man/man8 zic.8 zdump.8

	install -Dm644 -t "$DESTDIR"/usr/share/zoneinfo ./leap-seconds.list

  mkdir -p "$DESTDIR"/etc/sysconf.d/
  install tzdata.sysconf "$DESTDIR"/etc/sysconf.d/tzdata
}
