#!/usr/bin/env bash
name='qt6-networkauth'
release='5'
version='6.11.1'
url='https://www.qt.io/'
description='Network authentication module'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtnetworkauth-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake ninja)
sha256sums=('9f1d5bf22ccc033e42076186b964f9d4d4179fd0312a2c0f1aa19db42516563d')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtnetworkauth-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
