#!/usr/bin/env bash
name='kcontacts'
release='6'
version='6.27.0'
url='https://community.kde.org/Frameworks'
description='Address book API for KDE'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcontacts-${version}.tar.xz")
depends=(qt6-base kcoreaddons kconfig ki18n kcodecs)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=( 'dd8d6dd045b0fd71c7ce3fc18bb15b77ec8316e57f4d83ddae67f3a62b796efb' )
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

