#!/usr/bin/env bash
name='htop'
release='3'
version='3.5.3'
url='https://github.com/htop-dev/htop'
description='Interactive process viewer'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/htop-dev/htop/releases/download/$version/htop-$version.tar.xz")
depends=(libcap libnl libunwind ncurses)
makedepends=()
sha256sums=('a8b164386494cb85bb255a415a3f5f80afe7a0c4491da5d113b3a0f951087e65')
group=(sys.process)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    autoreconf -vfi
    ./configure --prefix=/usr \
        --enable-cgroup \
        --with-os-release=/dev/null \
        --enable-taskstats
}

build () {
    make $jobs
}

package () {
    make install pixmapdir=/usr/share/icons/hicolor/128x128/apps $jobs
}

