#!/usr/bin/env bash
name='htop'
release='2'
version='3.5.0'
url='https://github.com/htop-dev/htop'
description='Interactive process viewer'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/htop-dev/htop/releases/download/$version/htop-$version.tar.xz")
depends=(libcap libnl libunwind ncurses)
makedepends=()
sha256sums=('b6586e405c5223ebe5ac7828df21edad45cbf90288088bd1b18ad8fa700ffa05')
group=(sys.process)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    autoreconf -vfi
    ./configure --prefix=/usr \
        --enable-cgroup \
        --with-os-release=/dev/null \
        --enable-taskstats
}

build () {
    make $jobs
}

package () {
    make install pixmapdir=/usr/share/icons/hicolor/128x128/apps $jobs
}

