#!/usr/bin/env bash
name='wayland'
release='5'
version='1.25.0'
url='https://gitlab.freedesktop.org/wayland'
description='Core Wayland window system code and protocol'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland/-/archive/$version/wayland-$version.tar.gz")
depends=(zlib expat libffi xz-utils libxml2 mesa)
makedepends=()
sha256sums=('95413723f6cd0462770eda207a1c78d142d0a1bba9b0572a4ed1da6a9b27059c')
group=(dev.libs)
uses=()
uses_extra=(doc)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -Ddefault_library=both \
        -Ddocumentation=$(use_opt doc true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

