#!/usr/bin/env bash
name='hyprlang'
release='3'
version='0.6.7'
url='https://github.com/hyprwm/hyprlang'
description='The official implementation library for the hypr config language.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprlang/archive/refs/tags/v$version.tar.gz")
depends=(hyprutils glib)
makedepends=()
sha256sums=('e8d54af895ec04fe99553c68d1255dceddb43723ada4a134acdd46bfe1dbf924')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

