#!/usr/bin/env bash
name='hyprcursor'
release='3'
version='0.1.13'
url='https://github.com/hyprwm/hyprcursor'
description='The hyprland cursor format, library and utilities.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprcursor/archive/refs/tags/v$version.zip")
depends=(librsvg libzip tomlplusplus hyprlang)
makedepends=()
sha256sums=('cda02c7bdf60c82463995f52c2c80bfc691b61d11b5d57546bb8c4f6118a3958')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

