#!/usr/bin/env bash
name='libXpm'
release='2'
version='3.5.18'
url='https://gitlab.freedesktop.org/xorg/lib/libXpm.git/'
description='X.Org Xpm library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXpm-$version.tar.xz")
depends=(libX11)
makedepends=()
sha256sums=('b4ed79bfc718000edee837d551c35286f0b84576db0ce07bbbebe60a4affa1e4')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

