#!/usr/bin/env bash
name='bluez'
release='6'
version='5.86'
url='https://www.bluez.org'
description='Daemons for the bluetooth protocol stack'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://www.kernel.org/pub/linux/bluetooth/bluez-${version}.tar.xz"
        "bluetooth.initd")
depends=(glib dbus eudev json-c libical readline)
makedepends=(json-c alsa-lib ell)
sha256sums=('99f144540c6070591e4c53bcb977eb42664c62b7b36cb35a29cf72ded339621d'
         'SKIP')
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc     \
        --localstatedir=/var  \
        --enable-library      \
        --disable-manpages    \
        --disable-systemd \
		    --enable-deprecated \
        --enable-hid2hci \
        --enable-mesh \
        --enable-sixaxis
}

build(){
    make $jobs
}

package (){
    make install $jobs
    install -v -dm755 $DESTDIR/usr/sbin
    install -v -dm755 $DESTDIR/etc/init.d
    ln -svf ../libexec/bluetooth/bluetoothd $DESTDIR/usr/sbin/bluetoothd
    install -v -dm755 $DESTDIR/etc/bluetooth
    install -v -m644 src/main.conf $DESTDIR/etc/bluetooth/main.conf
    install -v -dm755 $DESTDIR/usr/share/doc/
    install -v -dm755 $DESTDIR/usr/share/doc/bluez-5.66
    install -v -m644 doc/*.txt $DESTDIR/usr/share/doc/bluez-5.66
    install ../bluetooth.initd $DESTDIR/etc/init.d/bluetooth
}
