#!/usr/bin/env bash
name='kscreenlocker'
release='6'
version='6.7.0'
url='https://kde.org/plasma-desktop'
description='Library and components for secure lock screen architecture'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kscreenlocker-${version}.tar.xz"
"kde.pam"
"kde-np.pam"
"kde-fingerprint.pam")
depends=(kconfig kcoreaddons kcrash kdeclarative kglobalaccel ki18n kidletime kio kirigami knotifications kpackage ksvg
         kwindowsystem kxmlgui layer-shell-qt libkscreen libX11 libxcb libXi pam libplasma qt6-base qt6-declarative wayland
         xcb-util-keysyms)
makedepends=(extra-cmake-modules kdoctools kcmutils)
