#!/usr/bin/env bash
name='libXfixes'
release='2'
version='6.0.2'
url='https://gitlab.freedesktop.org/xorg/lib/libXfixes.git/'
description='X.Org Xfixes library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXfixes-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('041331b8e6e36038b3bf836785b6b175ec8515f964c9e4e3316b3bfed0f53ac7')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

