#!/usr/bin/env bash
name='dolphin'
release='6'
version='26.04.2'
url='https://apps.kde.org/dolphin/'
description='KDE File Manager'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/dolphin-${version}.tar.xz")
depends=(baloo-widgets knewstuff kcmutils kparts phonon ktextwidgets)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=( 'c7e90beb8ce13aea091494ae7ddfabde999b1297986a596403828010bec59346' )
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd

	rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop
	ln -s ../applications/org.kde.dolphin.desktop $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop

}

