#!/usr/bin/env bash
name='libXft'
release='2'
version='2.3.9'
url='https://gitlab.freedesktop.org/xorg/lib/libXft.git/'
description='XFreeType-based font drawing library for X'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXft-$version.tar.xz")
depends=(fontconfig libXrender)
makedepends=()
sha256sums=('60a25b78945ed6932635b3bb1899a517d31df7456e69867ffba27f89ff3976f5')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

