#!/usr/bin/env bash
name='libwacom'
release='5'
version='2.17.0'
url='https://github.com/linuxwacom/libwacom/wiki'
description='Library to help implement Wacom tablet settings'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/linuxwacom/libwacom/releases/download/libwacom-${version}/libwacom-${version}.tar.xz")
depends=(eudev)
makedepends=(meson)
sha256sums=('41a0f239841567b101904df8ced81e1e0115334ccfd82a024412aa0903dae5a7')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build  \
      --prefix=/usr   \
      --buildtype=release \
      -Dtests=disabled
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
	install -D -m644 COPYING "${DESTDIR}/usr/share/licenses/${name}/LICENSE"
}
