#!/usr/bin/env bash
name='py3-urllib3'
release='3'
version='2.7.0'
url='https://github.com/urllib3/urllib3'
description='HTTP library with thread-safe connection pooling, file post, and more'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/urllib3/urllib3/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-sphinx py3-wheel py3-hatchling)
sha256sums=('74317bc088603618b7bd9a57d7f3a043cef29123b672a5c280d373f5b3a8c317')
group=(dev.python)
uses=()
arch=('x86_64')

export SETUPTOOLS_SCM_PRETEND_VERSION=$version

cd "urllib3"-$version


build(){
	python -m build --wheel

}

package(){
	python -m installer --destdir="$DESTDIR" dist/*.whl
	mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

